from collections.abc import Iterable as _Iterable
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

DESCRIPTOR: _descriptor.FileDescriptor

class TIME_TASK_MODE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    TIME_TASK_MODE_RESV: _ClassVar[TIME_TASK_MODE]
    TIME_TASK_MODE_PER_WEEK: _ClassVar[TIME_TASK_MODE]
    TIME_TASK_MODE_ONCE: _ClassVar[TIME_TASK_MODE]

class TIME_TASK_TYPE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    TIME_TASK_TYPE_AC_CHG: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_AC_DSG: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_AC2_DSG: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_DC_CHG: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_DC2_CHG: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_DC_DSG: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_OIL_ON: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_OIL_OFF: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_USB_CHG: _ClassVar[TIME_TASK_TYPE]
    TIME_TASK_TYPE_USB_DSG: _ClassVar[TIME_TASK_TYPE]

class TIME_TASK_DETAIL_TYPE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    TIME_TASK_DETAIL_IDLE: _ClassVar[TIME_TASK_DETAIL_TYPE]
    TIME_TASK_DETAIL_POW: _ClassVar[TIME_TASK_DETAIL_TYPE]
    TIME_TASK_DETAIL_TEMP: _ClassVar[TIME_TASK_DETAIL_TYPE]
    TIME_TASK_DETAIL_LEVEL: _ClassVar[TIME_TASK_DETAIL_TYPE]
TIME_TASK_MODE_RESV: TIME_TASK_MODE
TIME_TASK_MODE_PER_WEEK: TIME_TASK_MODE
TIME_TASK_MODE_ONCE: TIME_TASK_MODE
TIME_TASK_TYPE_AC_CHG: TIME_TASK_TYPE
TIME_TASK_TYPE_AC_DSG: TIME_TASK_TYPE
TIME_TASK_TYPE_AC2_DSG: TIME_TASK_TYPE
TIME_TASK_TYPE_DC_CHG: TIME_TASK_TYPE
TIME_TASK_TYPE_DC2_CHG: TIME_TASK_TYPE
TIME_TASK_TYPE_DC_DSG: TIME_TASK_TYPE
TIME_TASK_TYPE_OIL_ON: TIME_TASK_TYPE
TIME_TASK_TYPE_OIL_OFF: TIME_TASK_TYPE
TIME_TASK_TYPE_USB_CHG: TIME_TASK_TYPE
TIME_TASK_TYPE_USB_DSG: TIME_TASK_TYPE
TIME_TASK_DETAIL_IDLE: TIME_TASK_DETAIL_TYPE
TIME_TASK_DETAIL_POW: TIME_TASK_DETAIL_TYPE
TIME_TASK_DETAIL_TEMP: TIME_TASK_DETAIL_TYPE
TIME_TASK_DETAIL_LEVEL: TIME_TASK_DETAIL_TYPE

class DP3Header(_message.Message):
    __slots__ = ("ack_type", "check_type", "cmd_func", "cmd_id", "code", "d_dest", "d_src", "data_len", "dest", "device_sn", "enc_type", "is_ack", "is_queue", "is_rw_cmd", "module_sn", "need_ack", "payload_ver", "pdata", "product_id", "seq", "src", "time_snap", "version")
    PDATA_FIELD_NUMBER: _ClassVar[int]
    SRC_FIELD_NUMBER: _ClassVar[int]
    DEST_FIELD_NUMBER: _ClassVar[int]
    D_SRC_FIELD_NUMBER: _ClassVar[int]
    D_DEST_FIELD_NUMBER: _ClassVar[int]
    ENC_TYPE_FIELD_NUMBER: _ClassVar[int]
    CHECK_TYPE_FIELD_NUMBER: _ClassVar[int]
    CMD_FUNC_FIELD_NUMBER: _ClassVar[int]
    CMD_ID_FIELD_NUMBER: _ClassVar[int]
    DATA_LEN_FIELD_NUMBER: _ClassVar[int]
    NEED_ACK_FIELD_NUMBER: _ClassVar[int]
    IS_ACK_FIELD_NUMBER: _ClassVar[int]
    SEQ_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_ID_FIELD_NUMBER: _ClassVar[int]
    VERSION_FIELD_NUMBER: _ClassVar[int]
    PAYLOAD_VER_FIELD_NUMBER: _ClassVar[int]
    TIME_SNAP_FIELD_NUMBER: _ClassVar[int]
    IS_RW_CMD_FIELD_NUMBER: _ClassVar[int]
    IS_QUEUE_FIELD_NUMBER: _ClassVar[int]
    ACK_TYPE_FIELD_NUMBER: _ClassVar[int]
    CODE_FIELD_NUMBER: _ClassVar[int]
    FROM_FIELD_NUMBER: _ClassVar[int]
    MODULE_SN_FIELD_NUMBER: _ClassVar[int]
    DEVICE_SN_FIELD_NUMBER: _ClassVar[int]
    pdata: bytes
    src: int
    dest: int
    d_src: int
    d_dest: int
    enc_type: int
    check_type: int
    cmd_func: int
    cmd_id: int
    data_len: int
    need_ack: int
    is_ack: int
    seq: int
    product_id: int
    version: int
    payload_ver: int
    time_snap: int
    is_rw_cmd: int
    is_queue: int
    ack_type: int
    code: str
    module_sn: str
    device_sn: str
    def __init__(self, pdata: bytes | None = ..., src: int | None = ..., dest: int | None = ..., d_src: int | None = ..., d_dest: int | None = ..., enc_type: int | None = ..., check_type: int | None = ..., cmd_func: int | None = ..., cmd_id: int | None = ..., data_len: int | None = ..., need_ack: int | None = ..., is_ack: int | None = ..., seq: int | None = ..., product_id: int | None = ..., version: int | None = ..., payload_ver: int | None = ..., time_snap: int | None = ..., is_rw_cmd: int | None = ..., is_queue: int | None = ..., ack_type: int | None = ..., code: str | None = ..., module_sn: str | None = ..., device_sn: str | None = ..., **kwargs) -> None: ...

class DP3SendHeaderMsg(_message.Message):
    __slots__ = ("msg",)
    MSG_FIELD_NUMBER: _ClassVar[int]
    msg: _containers.RepeatedCompositeFieldContainer[DP3Header]
    def __init__(self, msg: _Iterable[DP3Header | _Mapping] | None = ...) -> None: ...

class DP3RuntimePropertyUpload(_message.Message):
    __slots__ = ("ac_phase_type", "ads_ntc_temp", "bms_alm_state", "bms_alm_state_2", "bms_bal_state", "bms_batt_amp", "bms_batt_vol", "bms_err_code", "bms_firm_ver", "bms_flt_state", "bms_full_cap", "bms_high_temp_icon", "bms_limit_icon", "bms_low_temp_icon", "bms_max_cell_vol", "bms_min_cell_vol", "bms_overload_icon", "bms_pro_state", "bms_pro_state_2", "bms_remain_cap", "bms_warn_icon", "cms_batt_amp", "cms_batt_vol", "cms_chg_req_amp", "cms_chg_req_vol", "dcdc_chg_req_cur", "display_property_full_upload_period", "display_property_incremental_upload_period", "inv_bus_vol", "inv_main_fsmstate", "inv_monitor_flag", "inv_ntc_temp2", "inv_ntc_temp3", "inv_to_llc_ac_pow_lim", "iot_firm_ver", "l1_main_fsmstate", "l2_main_fsmstate", "llc_bat_cur", "llc_bat_vol", "llc_bus_vol", "llc_firm_ver", "llc_fsmstate", "llc_inv_firm_ver", "llc_monitor_flag", "llc_ntc_temp", "llc_recv_cms_chg_req_vol", "mppt_bat_amp", "mppt_bat_vol", "mppt_fanspeed", "mppt_firm_ver", "mppt_hardware_ver", "mppt_monitor_flag", "mppt_recv_cms_chg_req_amp", "mppt_recv_cms_chg_req_vol", "pcs_work_mode", "pd_bms_comm_err", "pd_firm_ver", "pd_iot_comm_err", "pd_llc_comm_err", "pd_mppt_comm_err", "pd_skt_ocp1", "pd_skt_ocp2", "pd_skt_ocp3", "pd_skt_ocp4", "pd_skt_ocp5", "pd_to_inv_dsg_mode", "plug_in_info_4p8_1_amp", "plug_in_info_4p8_1_vol", "plug_in_info_4p8_2_amp", "plug_in_info_4p8_2_vol", "plug_in_info_5p8_freq", "plug_in_info_12v_amp", "plug_in_info_12v_vol", "plug_in_info_24v_amp", "plug_in_info_24v_vol", "plug_in_info_ac_in_amp", "plug_in_info_ac_in_vol", "plug_in_info_ac_out_freq", "plug_in_info_ac_out_type", "plug_in_info_acp_l1_vol", "plug_in_info_acp_l1l2_vol", "plug_in_info_bms_vol", "plug_in_info_l1_amp", "plug_in_info_l1_vol", "plug_in_info_l2_amp", "plug_in_info_l2_vol", "plug_in_info_pfc_out_vol", "plug_in_info_pv_h_amp", "plug_in_info_pv_h_vol", "plug_in_info_pv_l_amp", "plug_in_info_pv_l_vol", "pow_get_l1", "pow_get_l2", "pv2_bus_vol", "pv2_pause_cnt", "pv2_vin_ref", "pv_pause_cnt", "pv_vin_ref", "runtime_property_full_upload_period", "runtime_property_incremental_upload_period", "temp_pcs_ac", "temp_pcs_dc", "temp_pv_h", "temp_pv_l")
    AC_PHASE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PCS_WORK_MODE_FIELD_NUMBER: _ClassVar[int]
    TEMP_PCS_DC_FIELD_NUMBER: _ClassVar[int]
    TEMP_PCS_AC_FIELD_NUMBER: _ClassVar[int]
    TEMP_PV_H_FIELD_NUMBER: _ClassVar[int]
    TEMP_PV_L_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_FREQ_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_24V_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_24V_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_L1_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_BMS_VOL_FIELD_NUMBER: _ClassVar[int]
    PD_MPPT_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_LLC_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_BMS_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_IOT_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    IOT_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    MPPT_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    LLC_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_L1_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_L2_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_L2_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_ACP_L1_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_ACP_L1L2_VOL_FIELD_NUMBER: _ClassVar[int]
    MPPT_MONITOR_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_AMP_FIELD_NUMBER: _ClassVar[int]
    LLC_INV_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_VOL_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_BAL_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_FULL_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_REMAIN_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_ALM_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_PRO_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_FLT_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_AMP_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_OVERLOAD_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_WARN_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_HIGH_TEMP_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_LOW_TEMP_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_LIMIT_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_ALM_STATE_2_FIELD_NUMBER: _ClassVar[int]
    BMS_PRO_STATE_2_FIELD_NUMBER: _ClassVar[int]
    DISPLAY_PROPERTY_FULL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    DISPLAY_PROPERTY_INCREMENTAL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    RUNTIME_PROPERTY_FULL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    RUNTIME_PROPERTY_INCREMENTAL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    MPPT_RECV_CMS_CHG_REQ_VOL_FIELD_NUMBER: _ClassVar[int]
    MPPT_RECV_CMS_CHG_REQ_AMP_FIELD_NUMBER: _ClassVar[int]
    PV_VIN_REF_FIELD_NUMBER: _ClassVar[int]
    PV2_VIN_REF_FIELD_NUMBER: _ClassVar[int]
    PV2_BUS_VOL_FIELD_NUMBER: _ClassVar[int]
    MPPT_BAT_VOL_FIELD_NUMBER: _ClassVar[int]
    MPPT_BAT_AMP_FIELD_NUMBER: _ClassVar[int]
    PV_PAUSE_CNT_FIELD_NUMBER: _ClassVar[int]
    PV2_PAUSE_CNT_FIELD_NUMBER: _ClassVar[int]
    MPPT_FANSPEED_FIELD_NUMBER: _ClassVar[int]
    ADS_NTC_TEMP_FIELD_NUMBER: _ClassVar[int]
    MPPT_HARDWARE_VER_FIELD_NUMBER: _ClassVar[int]
    INV_MONITOR_FLAG_FIELD_NUMBER: _ClassVar[int]
    INV_MAIN_FSMSTATE_FIELD_NUMBER: _ClassVar[int]
    L1_MAIN_FSMSTATE_FIELD_NUMBER: _ClassVar[int]
    L2_MAIN_FSMSTATE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PFC_OUT_VOL_FIELD_NUMBER: _ClassVar[int]
    POW_GET_L1_FIELD_NUMBER: _ClassVar[int]
    POW_GET_L2_FIELD_NUMBER: _ClassVar[int]
    INV_BUS_VOL_FIELD_NUMBER: _ClassVar[int]
    INV_NTC_TEMP2_FIELD_NUMBER: _ClassVar[int]
    INV_NTC_TEMP3_FIELD_NUMBER: _ClassVar[int]
    LLC_MONITOR_FLAG_FIELD_NUMBER: _ClassVar[int]
    LLC_NTC_TEMP_FIELD_NUMBER: _ClassVar[int]
    LLC_FSMSTATE_FIELD_NUMBER: _ClassVar[int]
    PD_TO_INV_DSG_MODE_FIELD_NUMBER: _ClassVar[int]
    DCDC_CHG_REQ_CUR_FIELD_NUMBER: _ClassVar[int]
    LLC_RECV_CMS_CHG_REQ_VOL_FIELD_NUMBER: _ClassVar[int]
    INV_TO_LLC_AC_POW_LIM_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_12V_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_12V_AMP_FIELD_NUMBER: _ClassVar[int]
    LLC_BAT_VOL_FIELD_NUMBER: _ClassVar[int]
    LLC_BAT_CUR_FIELD_NUMBER: _ClassVar[int]
    LLC_BUS_VOL_FIELD_NUMBER: _ClassVar[int]
    PD_SKT_OCP1_FIELD_NUMBER: _ClassVar[int]
    PD_SKT_OCP2_FIELD_NUMBER: _ClassVar[int]
    PD_SKT_OCP3_FIELD_NUMBER: _ClassVar[int]
    PD_SKT_OCP4_FIELD_NUMBER: _ClassVar[int]
    PD_SKT_OCP5_FIELD_NUMBER: _ClassVar[int]
    ac_phase_type: int
    pcs_work_mode: int
    temp_pcs_dc: float
    temp_pcs_ac: float
    temp_pv_h: float
    temp_pv_l: float
    plug_in_info_pv_h_vol: float
    plug_in_info_pv_l_vol: float
    plug_in_info_ac_out_type: int
    plug_in_info_ac_out_freq: int
    plug_in_info_5p8_freq: int
    plug_in_info_ac_in_vol: float
    plug_in_info_24v_vol: float
    plug_in_info_24v_amp: float
    plug_in_info_l1_vol: float
    plug_in_info_4p8_1_vol: float
    plug_in_info_4p8_2_vol: float
    plug_in_info_bms_vol: float
    pd_mppt_comm_err: int
    pd_llc_comm_err: int
    pd_bms_comm_err: int
    pd_iot_comm_err: int
    pd_firm_ver: int
    iot_firm_ver: int
    mppt_firm_ver: int
    llc_firm_ver: int
    plug_in_info_l1_amp: float
    plug_in_info_l2_vol: float
    plug_in_info_l2_amp: float
    plug_in_info_acp_l1_vol: float
    plug_in_info_acp_l1l2_vol: float
    mppt_monitor_flag: int
    plug_in_info_pv_h_amp: float
    plug_in_info_pv_l_amp: float
    plug_in_info_ac_in_amp: float
    llc_inv_firm_ver: int
    plug_in_info_4p8_1_amp: float
    plug_in_info_4p8_2_amp: float
    bms_firm_ver: int
    bms_batt_vol: float
    bms_batt_amp: float
    bms_bal_state: int
    bms_full_cap: int
    bms_remain_cap: int
    bms_alm_state: int
    bms_pro_state: int
    bms_flt_state: int
    bms_err_code: int
    bms_min_cell_vol: int
    bms_max_cell_vol: int
    cms_batt_vol: float
    cms_batt_amp: float
    cms_chg_req_vol: float
    cms_chg_req_amp: float
    bms_overload_icon: int
    bms_warn_icon: int
    bms_high_temp_icon: int
    bms_low_temp_icon: int
    bms_limit_icon: int
    bms_alm_state_2: int
    bms_pro_state_2: int
    display_property_full_upload_period: int
    display_property_incremental_upload_period: int
    runtime_property_full_upload_period: int
    runtime_property_incremental_upload_period: int
    mppt_recv_cms_chg_req_vol: float
    mppt_recv_cms_chg_req_amp: float
    pv_vin_ref: float
    pv2_vin_ref: float
    pv2_bus_vol: float
    mppt_bat_vol: float
    mppt_bat_amp: float
    pv_pause_cnt: int
    pv2_pause_cnt: int
    mppt_fanspeed: int
    ads_ntc_temp: int
    mppt_hardware_ver: int
    inv_monitor_flag: int
    inv_main_fsmstate: int
    l1_main_fsmstate: int
    l2_main_fsmstate: int
    plug_in_info_pfc_out_vol: float
    pow_get_l1: float
    pow_get_l2: float
    inv_bus_vol: float
    inv_ntc_temp2: int
    inv_ntc_temp3: int
    llc_monitor_flag: int
    llc_ntc_temp: int
    llc_fsmstate: int
    pd_to_inv_dsg_mode: int
    dcdc_chg_req_cur: float
    llc_recv_cms_chg_req_vol: float
    inv_to_llc_ac_pow_lim: float
    plug_in_info_12v_vol: float
    plug_in_info_12v_amp: float
    llc_bat_vol: float
    llc_bat_cur: float
    llc_bus_vol: float
    pd_skt_ocp1: float
    pd_skt_ocp2: float
    pd_skt_ocp3: float
    pd_skt_ocp4: float
    pd_skt_ocp5: float
    def __init__(self, ac_phase_type: int | None = ..., pcs_work_mode: int | None = ..., temp_pcs_dc: float | None = ..., temp_pcs_ac: float | None = ..., temp_pv_h: float | None = ..., temp_pv_l: float | None = ..., plug_in_info_pv_h_vol: float | None = ..., plug_in_info_pv_l_vol: float | None = ..., plug_in_info_ac_out_type: int | None = ..., plug_in_info_ac_out_freq: int | None = ..., plug_in_info_5p8_freq: int | None = ..., plug_in_info_ac_in_vol: float | None = ..., plug_in_info_24v_vol: float | None = ..., plug_in_info_24v_amp: float | None = ..., plug_in_info_l1_vol: float | None = ..., plug_in_info_4p8_1_vol: float | None = ..., plug_in_info_4p8_2_vol: float | None = ..., plug_in_info_bms_vol: float | None = ..., pd_mppt_comm_err: int | None = ..., pd_llc_comm_err: int | None = ..., pd_bms_comm_err: int | None = ..., pd_iot_comm_err: int | None = ..., pd_firm_ver: int | None = ..., iot_firm_ver: int | None = ..., mppt_firm_ver: int | None = ..., llc_firm_ver: int | None = ..., plug_in_info_l1_amp: float | None = ..., plug_in_info_l2_vol: float | None = ..., plug_in_info_l2_amp: float | None = ..., plug_in_info_acp_l1_vol: float | None = ..., plug_in_info_acp_l1l2_vol: float | None = ..., mppt_monitor_flag: int | None = ..., plug_in_info_pv_h_amp: float | None = ..., plug_in_info_pv_l_amp: float | None = ..., plug_in_info_ac_in_amp: float | None = ..., llc_inv_firm_ver: int | None = ..., plug_in_info_4p8_1_amp: float | None = ..., plug_in_info_4p8_2_amp: float | None = ..., bms_firm_ver: int | None = ..., bms_batt_vol: float | None = ..., bms_batt_amp: float | None = ..., bms_bal_state: int | None = ..., bms_full_cap: int | None = ..., bms_remain_cap: int | None = ..., bms_alm_state: int | None = ..., bms_pro_state: int | None = ..., bms_flt_state: int | None = ..., bms_err_code: int | None = ..., bms_min_cell_vol: int | None = ..., bms_max_cell_vol: int | None = ..., cms_batt_vol: float | None = ..., cms_batt_amp: float | None = ..., cms_chg_req_vol: float | None = ..., cms_chg_req_amp: float | None = ..., bms_overload_icon: int | None = ..., bms_warn_icon: int | None = ..., bms_high_temp_icon: int | None = ..., bms_low_temp_icon: int | None = ..., bms_limit_icon: int | None = ..., bms_alm_state_2: int | None = ..., bms_pro_state_2: int | None = ..., display_property_full_upload_period: int | None = ..., display_property_incremental_upload_period: int | None = ..., runtime_property_full_upload_period: int | None = ..., runtime_property_incremental_upload_period: int | None = ..., mppt_recv_cms_chg_req_vol: float | None = ..., mppt_recv_cms_chg_req_amp: float | None = ..., pv_vin_ref: float | None = ..., pv2_vin_ref: float | None = ..., pv2_bus_vol: float | None = ..., mppt_bat_vol: float | None = ..., mppt_bat_amp: float | None = ..., pv_pause_cnt: int | None = ..., pv2_pause_cnt: int | None = ..., mppt_fanspeed: int | None = ..., ads_ntc_temp: int | None = ..., mppt_hardware_ver: int | None = ..., inv_monitor_flag: int | None = ..., inv_main_fsmstate: int | None = ..., l1_main_fsmstate: int | None = ..., l2_main_fsmstate: int | None = ..., plug_in_info_pfc_out_vol: float | None = ..., pow_get_l1: float | None = ..., pow_get_l2: float | None = ..., inv_bus_vol: float | None = ..., inv_ntc_temp2: int | None = ..., inv_ntc_temp3: int | None = ..., llc_monitor_flag: int | None = ..., llc_ntc_temp: int | None = ..., llc_fsmstate: int | None = ..., pd_to_inv_dsg_mode: int | None = ..., dcdc_chg_req_cur: float | None = ..., llc_recv_cms_chg_req_vol: float | None = ..., inv_to_llc_ac_pow_lim: float | None = ..., plug_in_info_12v_vol: float | None = ..., plug_in_info_12v_amp: float | None = ..., llc_bat_vol: float | None = ..., llc_bat_cur: float | None = ..., llc_bus_vol: float | None = ..., pd_skt_ocp1: float | None = ..., pd_skt_ocp2: float | None = ..., pd_skt_ocp3: float | None = ..., pd_skt_ocp4: float | None = ..., pd_skt_ocp5: float | None = ...) -> None: ...

class DP3BMSDetailedReport(_message.Message):
    __slots__ = ("bat_volt_mv_array", "bms_alm_state", "bms_bal_state", "bms_batt_amp", "bms_batt_soc_percent_float1", "bms_batt_soc_percent_float2", "bms_batt_soc_percent_float3", "bms_batt_soh_percent_float", "bms_batt_soh_percent_int", "bms_batt_vol", "bms_chg_dsg_state", "bms_chg_rem_time_min", "bms_design_cap_mah", "bms_design_cap_mah_dup", "bms_dsg_rem_time_min", "bms_err_code_flags", "bms_firm_ver", "bms_flt_state", "bms_full_cap_mah", "bms_heart_ver", "bms_max_cell_temp_dup", "bms_pro_state", "bms_remain_cap_mah", "bms_sn", "cell_temp_array_size", "cell_temp_c", "cell_vol_array_size", "cell_vol_mv", "ecloud_ocv", "max_cell_temp_c", "max_cell_vol_mv", "max_mos_temp_c", "max_mos_temp_c_dup", "min_cell_temp_c", "min_cell_vol_mv", "min_mos_temp_c", "mos_temp_c", "pack_sn", "unknown5", "unknown6", "unknown10", "unknown14", "unknown22", "unknown23", "unknown26", "unknown29", "unknown30", "unknown40", "unknown41", "unknown43", "unknown45", "unknown46", "unknown48", "unknown49", "unknown50", "unknown51", "unknown52", "unknown53", "unknown55", "unknown57", "unknown58", "unknown61", "unknown62", "unknown63", "unknown64", "unknown67", "unknown68", "unknown69", "unknown71", "unknown73", "unknown74", "unknown75", "unknown76", "unknown77", "unknown78", "unknown79", "unknown80", "unknown82")
    BMS_FLT_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_PRO_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_ALM_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_BAL_STATE_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN5_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN6_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_VOL_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_CELL_TEMP_DUP_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN10_FIELD_NUMBER: _ClassVar[int]
    BMS_DESIGN_CAP_MAH_DUP_FIELD_NUMBER: _ClassVar[int]
    BMS_REMAIN_CAP_MAH_FIELD_NUMBER: _ClassVar[int]
    BMS_FULL_CAP_MAH_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN14_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOH_PERCENT_INT_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_VOL_MV_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_VOL_MV_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_TEMP_C_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_TEMP_C_FIELD_NUMBER: _ClassVar[int]
    MAX_MOS_TEMP_C_FIELD_NUMBER: _ClassVar[int]
    MIN_MOS_TEMP_C_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN22_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN23_FIELD_NUMBER: _ClassVar[int]
    BMS_DESIGN_CAP_MAH_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOC_PERCENT_FLOAT1_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN26_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_REM_TIME_MIN_FIELD_NUMBER: _ClassVar[int]
    BMS_DSG_REM_TIME_MIN_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN29_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN30_FIELD_NUMBER: _ClassVar[int]
    MAX_MOS_TEMP_C_DUP_FIELD_NUMBER: _ClassVar[int]
    CELL_VOL_ARRAY_SIZE_FIELD_NUMBER: _ClassVar[int]
    CELL_VOL_MV_FIELD_NUMBER: _ClassVar[int]
    CELL_TEMP_ARRAY_SIZE_FIELD_NUMBER: _ClassVar[int]
    CELL_TEMP_C_FIELD_NUMBER: _ClassVar[int]
    BMS_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_HEART_VER_FIELD_NUMBER: _ClassVar[int]
    ECLOUD_OCV_FIELD_NUMBER: _ClassVar[int]
    BMS_SN_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN40_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN41_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOC_PERCENT_FLOAT2_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN43_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOC_PERCENT_FLOAT3_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN45_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN46_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN48_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN49_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN50_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN51_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN52_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN53_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOH_PERCENT_FLOAT_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN55_FIELD_NUMBER: _ClassVar[int]
    MOS_TEMP_C_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN57_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN58_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN61_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN62_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN63_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN64_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN67_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN68_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN69_FIELD_NUMBER: _ClassVar[int]
    BMS_ERR_CODE_FLAGS_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN71_FIELD_NUMBER: _ClassVar[int]
    BAT_VOLT_MV_ARRAY_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN73_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN74_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN75_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN76_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN77_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN78_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN79_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN80_FIELD_NUMBER: _ClassVar[int]
    PACK_SN_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN82_FIELD_NUMBER: _ClassVar[int]
    bms_flt_state: int
    bms_pro_state: int
    bms_alm_state: int
    bms_bal_state: int
    unknown5: int
    unknown6: int
    bms_batt_vol: int
    bms_batt_amp: int
    bms_max_cell_temp_dup: int
    unknown10: int
    bms_design_cap_mah_dup: int
    bms_remain_cap_mah: int
    bms_full_cap_mah: int
    unknown14: int
    bms_batt_soh_percent_int: int
    max_cell_vol_mv: int
    min_cell_vol_mv: int
    max_cell_temp_c: int
    min_cell_temp_c: int
    max_mos_temp_c: int
    min_mos_temp_c: int
    unknown22: int
    unknown23: int
    bms_design_cap_mah: int
    bms_batt_soc_percent_float1: float
    unknown26: int
    bms_chg_rem_time_min: int
    bms_dsg_rem_time_min: int
    unknown29: int
    unknown30: int
    max_mos_temp_c_dup: int
    cell_vol_array_size: int
    cell_vol_mv: _containers.RepeatedScalarFieldContainer[int]
    cell_temp_array_size: int
    cell_temp_c: _containers.RepeatedScalarFieldContainer[int]
    bms_firm_ver: str
    bms_heart_ver: int
    ecloud_ocv: int
    bms_sn: str
    unknown40: int
    unknown41: int
    bms_batt_soc_percent_float2: float
    unknown43: float
    bms_batt_soc_percent_float3: float
    unknown45: int
    unknown46: int
    bms_chg_dsg_state: int
    unknown48: int
    unknown49: int
    unknown50: int
    unknown51: int
    unknown52: float
    unknown53: float
    bms_batt_soh_percent_float: float
    unknown55: int
    mos_temp_c: _containers.RepeatedScalarFieldContainer[int]
    unknown57: int
    unknown58: _containers.RepeatedScalarFieldContainer[int]
    unknown61: int
    unknown62: _containers.RepeatedScalarFieldContainer[int]
    unknown63: int
    unknown64: int
    unknown67: int
    unknown68: int
    unknown69: int
    bms_err_code_flags: _containers.RepeatedScalarFieldContainer[int]
    unknown71: int
    bat_volt_mv_array: _containers.RepeatedScalarFieldContainer[int]
    unknown73: int
    unknown74: int
    unknown75: int
    unknown76: int
    unknown77: int
    unknown78: int
    unknown79: int
    unknown80: int
    pack_sn: str
    unknown82: int
    def __init__(self, bms_flt_state: int | None = ..., bms_pro_state: int | None = ..., bms_alm_state: int | None = ..., bms_bal_state: int | None = ..., unknown5: int | None = ..., unknown6: int | None = ..., bms_batt_vol: int | None = ..., bms_batt_amp: int | None = ..., bms_max_cell_temp_dup: int | None = ..., unknown10: int | None = ..., bms_design_cap_mah_dup: int | None = ..., bms_remain_cap_mah: int | None = ..., bms_full_cap_mah: int | None = ..., unknown14: int | None = ..., bms_batt_soh_percent_int: int | None = ..., max_cell_vol_mv: int | None = ..., min_cell_vol_mv: int | None = ..., max_cell_temp_c: int | None = ..., min_cell_temp_c: int | None = ..., max_mos_temp_c: int | None = ..., min_mos_temp_c: int | None = ..., unknown22: int | None = ..., unknown23: int | None = ..., bms_design_cap_mah: int | None = ..., bms_batt_soc_percent_float1: float | None = ..., unknown26: int | None = ..., bms_chg_rem_time_min: int | None = ..., bms_dsg_rem_time_min: int | None = ..., unknown29: int | None = ..., unknown30: int | None = ..., max_mos_temp_c_dup: int | None = ..., cell_vol_array_size: int | None = ..., cell_vol_mv: _Iterable[int] | None = ..., cell_temp_array_size: int | None = ..., cell_temp_c: _Iterable[int] | None = ..., bms_firm_ver: str | None = ..., bms_heart_ver: int | None = ..., ecloud_ocv: int | None = ..., bms_sn: str | None = ..., unknown40: int | None = ..., unknown41: int | None = ..., bms_batt_soc_percent_float2: float | None = ..., unknown43: float | None = ..., bms_batt_soc_percent_float3: float | None = ..., unknown45: int | None = ..., unknown46: int | None = ..., bms_chg_dsg_state: int | None = ..., unknown48: int | None = ..., unknown49: int | None = ..., unknown50: int | None = ..., unknown51: int | None = ..., unknown52: float | None = ..., unknown53: float | None = ..., bms_batt_soh_percent_float: float | None = ..., unknown55: int | None = ..., mos_temp_c: _Iterable[int] | None = ..., unknown57: int | None = ..., unknown58: _Iterable[int] | None = ..., unknown61: int | None = ..., unknown62: _Iterable[int] | None = ..., unknown63: int | None = ..., unknown64: int | None = ..., unknown67: int | None = ..., unknown68: int | None = ..., unknown69: int | None = ..., bms_err_code_flags: _Iterable[int] | None = ..., unknown71: int | None = ..., bat_volt_mv_array: _Iterable[int] | None = ..., unknown73: int | None = ..., unknown74: int | None = ..., unknown75: int | None = ..., unknown76: int | None = ..., unknown77: int | None = ..., unknown78: int | None = ..., unknown79: int | None = ..., unknown80: int | None = ..., pack_sn: str | None = ..., unknown82: int | None = ...) -> None: ...

class DP3TimeTaskParamDetail(_message.Message):
    __slots__ = ("type", "val")
    TYPE_FIELD_NUMBER: _ClassVar[int]
    VAL_FIELD_NUMBER: _ClassVar[int]
    type: TIME_TASK_DETAIL_TYPE
    val: float
    def __init__(self, type: TIME_TASK_DETAIL_TYPE | str | None = ..., val: float | None = ...) -> None: ...

class DP3TimeTaskItemV2(_message.Message):
    __slots__ = ("conflict_flag", "is_cfg", "is_enable", "task_index", "task_param", "task_param_detail", "task_type", "time_mode", "time_param", "time_table")
    TASK_INDEX_FIELD_NUMBER: _ClassVar[int]
    IS_CFG_FIELD_NUMBER: _ClassVar[int]
    IS_ENABLE_FIELD_NUMBER: _ClassVar[int]
    CONFLICT_FLAG_FIELD_NUMBER: _ClassVar[int]
    TIME_MODE_FIELD_NUMBER: _ClassVar[int]
    TIME_PARAM_FIELD_NUMBER: _ClassVar[int]
    TIME_TABLE_FIELD_NUMBER: _ClassVar[int]
    TASK_TYPE_FIELD_NUMBER: _ClassVar[int]
    TASK_PARAM_FIELD_NUMBER: _ClassVar[int]
    TASK_PARAM_DETAIL_FIELD_NUMBER: _ClassVar[int]
    task_index: int
    is_cfg: bool
    is_enable: bool
    conflict_flag: int
    time_mode: TIME_TASK_MODE
    time_param: int
    time_table: int
    task_type: TIME_TASK_TYPE
    task_param: int
    task_param_detail: _containers.RepeatedCompositeFieldContainer[DP3TimeTaskParamDetail]
    def __init__(self, task_index: int | None = ..., is_cfg: bool | None = ..., is_enable: bool | None = ..., conflict_flag: int | None = ..., time_mode: TIME_TASK_MODE | str | None = ..., time_param: int | None = ..., time_table: int | None = ..., task_type: TIME_TASK_TYPE | str | None = ..., task_param: int | None = ..., task_param_detail: _Iterable[DP3TimeTaskParamDetail | _Mapping] | None = ...) -> None: ...

class DP3DisplayPropertyUpload(_message.Message):
    __slots__ = ("ac_always_on_mini_soc", "ac_energy_saving_open", "ac_hv_always_on", "ac_lv_always_on", "ac_out_freq", "ac_standby_time", "ble_standby_time", "bms_batt_soc", "bms_batt_soh", "bms_chg_dsg_state", "bms_chg_rem_time", "bms_design_cap", "bms_dsg_rem_time", "bms_err_code", "bms_max_cell_temp", "bms_max_mos_temp", "bms_min_cell_temp", "bms_min_mos_temp", "cms_batt_soc", "cms_batt_soh", "cms_bms_run_state", "cms_chg_dsg_state", "cms_chg_rem_time", "cms_dsg_rem_time", "cms_max_chg_soc", "cms_min_dsg_soc", "cms_oil_off_soc", "cms_oil_on_soc", "cms_oil_self_start", "current_time_task_v2_item", "dc_standby_time", "dev_sleep_state", "dev_standby_time", "en_beep", "energy_backup_en", "energy_backup_start_soc", "energy_backup_state", "errcode", "fast_charge_switch", "flow_info_4p8_1_in", "flow_info_4p8_1_out", "flow_info_4p8_2_in", "flow_info_4p8_2_out", "flow_info_5p8_in", "flow_info_5p8_out", "flow_info_12v", "flow_info_24v", "flow_info_ac2dc", "flow_info_ac_hv_out", "flow_info_ac_in", "flow_info_ac_lv_out", "flow_info_bms_chg", "flow_info_bms_dsg", "flow_info_dc2ac", "flow_info_pv_h", "flow_info_pv_l", "flow_info_qcusb1", "flow_info_qcusb2", "flow_info_typec1", "flow_info_typec2", "generator_care_mode_open", "generator_care_mode_start_time", "generator_pv_hybrid_mode_open", "generator_pv_hybrid_mode_soc_max", "lcd_light", "llc_GFCI_flag", "llc_err_code", "llc_hv_lv_flag", "llc_inv_err_code", "mppt_err_code", "multi_bp_chg_dsg_mode", "output_power_off_memory", "pcs_fan_err_flag", "pcs_fan_level", "pd_err_code", "plug_in_info_4p8_1_charger_flag", "plug_in_info_4p8_1_detail", "plug_in_info_4p8_1_dsg_chg_type", "plug_in_info_4p8_1_err_code", "plug_in_info_4p8_1_firm_ver", "plug_in_info_4p8_1_in_flag", "plug_in_info_4p8_1_resv", "plug_in_info_4p8_1_run_state", "plug_in_info_4p8_1_sn", "plug_in_info_4p8_1_type", "plug_in_info_4p8_2_charger_flag", "plug_in_info_4p8_2_detail", "plug_in_info_4p8_2_dsg_chg_type", "plug_in_info_4p8_2_err_code", "plug_in_info_4p8_2_firm_ver", "plug_in_info_4p8_2_in_flag", "plug_in_info_4p8_2_resv", "plug_in_info_4p8_2_run_state", "plug_in_info_4p8_2_sn", "plug_in_info_4p8_2_type", "plug_in_info_5p8_charger_flag", "plug_in_info_5p8_chg_hal_pow_max", "plug_in_info_5p8_chg_pow_max", "plug_in_info_5p8_detail", "plug_in_info_5p8_dsg_chg", "plug_in_info_5p8_dsg_pow_max", "plug_in_info_5p8_err_code", "plug_in_info_5p8_firm_ver", "plug_in_info_5p8_flag", "plug_in_info_5p8_resv", "plug_in_info_5p8_run_state", "plug_in_info_5p8_sn", "plug_in_info_5p8_type", "plug_in_info_ac_charger_flag", "plug_in_info_ac_in_chg_hal_pow_max", "plug_in_info_ac_in_chg_pow_max", "plug_in_info_ac_in_feq", "plug_in_info_ac_in_flag", "plug_in_info_ac_out_dsg_pow_max", "plug_in_info_pv_h_charger_flag", "plug_in_info_pv_h_chg_amp_max", "plug_in_info_pv_h_chg_vol_max", "plug_in_info_pv_h_dc_amp_max", "plug_in_info_pv_h_flag", "plug_in_info_pv_h_type", "plug_in_info_pv_l_charger_flag", "plug_in_info_pv_l_chg_amp_max", "plug_in_info_pv_l_chg_vol_max", "plug_in_info_pv_l_dc_amp_max", "plug_in_info_pv_l_flag", "plug_in_info_pv_l_type", "pow_get_4p8_1", "pow_get_4p8_2", "pow_get_5p8", "pow_get_12v", "pow_get_24v", "pow_get_ac", "pow_get_ac_hv_out", "pow_get_ac_in", "pow_get_ac_lv_out", "pow_get_ac_lv_tt30_out", "pow_get_bms", "pow_get_llc", "pow_get_pv_h", "pow_get_pv_l", "pow_get_qcusb1", "pow_get_qcusb2", "pow_get_typec1", "pow_get_typec2", "pow_in_sum_w", "pow_out_sum_w", "screen_off_time", "time_task_change_cnt", "time_task_conflict_flag", "utc_set_mode", "utc_timezone", "utc_timezone_id", "xboost_en")
    ERRCODE_FIELD_NUMBER: _ClassVar[int]
    POW_IN_SUM_W_FIELD_NUMBER: _ClassVar[int]
    POW_OUT_SUM_W_FIELD_NUMBER: _ClassVar[int]
    LCD_LIGHT_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_STATE_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_EN_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_START_SOC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_QCUSB1_FIELD_NUMBER: _ClassVar[int]
    POW_GET_QCUSB2_FIELD_NUMBER: _ClassVar[int]
    POW_GET_TYPEC1_FIELD_NUMBER: _ClassVar[int]
    POW_GET_TYPEC2_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_QCUSB1_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_QCUSB2_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_TYPEC1_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_TYPEC2_FIELD_NUMBER: _ClassVar[int]
    DEV_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    SCREEN_OFF_TIME_FIELD_NUMBER: _ClassVar[int]
    AC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    DC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    AC_ALWAYS_ON_MINI_SOC_FIELD_NUMBER: _ClassVar[int]
    XBOOST_EN_FIELD_NUMBER: _ClassVar[int]
    PCS_FAN_LEVEL_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_PV_H_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_PV_L_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_12V_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_24V_FIELD_NUMBER: _ClassVar[int]
    POW_GET_PV_H_FIELD_NUMBER: _ClassVar[int]
    POW_GET_PV_L_FIELD_NUMBER: _ClassVar[int]
    POW_GET_12V_FIELD_NUMBER: _ClassVar[int]
    POW_GET_24V_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_TYPE_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC2DC_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_DC2AC_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC_IN_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC_HV_OUT_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC_LV_OUT_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_5P8_IN_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_5P8_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_LLC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_IN_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_HV_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_LV_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_LV_TT30_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_5P8_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_FEQ_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_DETAIL_FIELD_NUMBER: _ClassVar[int]
    CURRENT_TIME_TASK_V2_ITEM_FIELD_NUMBER: _ClassVar[int]
    UTC_TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    UTC_TIMEZONE_ID_FIELD_NUMBER: _ClassVar[int]
    UTC_SET_MODE_FIELD_NUMBER: _ClassVar[int]
    BMS_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_POWER_OFF_MEMORY_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_BMS_DSG_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_BMS_CHG_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_4P8_1_IN_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_4P8_1_OUT_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_4P8_2_IN_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_4P8_2_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_BMS_FIELD_NUMBER: _ClassVar[int]
    POW_GET_4P8_1_FIELD_NUMBER: _ClassVar[int]
    POW_GET_4P8_2_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_DETAIL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_DETAIL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    FAST_CHARGE_SWITCH_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_DSG_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_RESV_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_SN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_DSG_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_RESV_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_SN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_DSG_CHG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_RESV_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_SN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    EN_BEEP_FIELD_NUMBER: _ClassVar[int]
    LLC_GFCI_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    DEV_SLEEP_STATE_FIELD_NUMBER: _ClassVar[int]
    PD_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    LLC_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    MPPT_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_1_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_4P8_2_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PCS_FAN_ERR_FLAG_FIELD_NUMBER: _ClassVar[int]
    LLC_HV_LV_FLAG_FIELD_NUMBER: _ClassVar[int]
    LLC_INV_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_CHG_VOL_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_CHG_VOL_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_L_CHG_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_H_CHG_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_DSG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_DSG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOH_FIELD_NUMBER: _ClassVar[int]
    BMS_DESIGN_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOH_FIELD_NUMBER: _ClassVar[int]
    CMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_OIL_ON_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_OIL_OFF_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_OIL_SELF_START_FIELD_NUMBER: _ClassVar[int]
    CMS_BMS_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    AC_HV_ALWAYS_ON_FIELD_NUMBER: _ClassVar[int]
    AC_LV_ALWAYS_ON_FIELD_NUMBER: _ClassVar[int]
    TIME_TASK_CONFLICT_FLAG_FIELD_NUMBER: _ClassVar[int]
    TIME_TASK_CHANGE_CNT_FIELD_NUMBER: _ClassVar[int]
    BLE_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    GENERATOR_PV_HYBRID_MODE_OPEN_FIELD_NUMBER: _ClassVar[int]
    GENERATOR_PV_HYBRID_MODE_SOC_MAX_FIELD_NUMBER: _ClassVar[int]
    GENERATOR_CARE_MODE_OPEN_FIELD_NUMBER: _ClassVar[int]
    GENERATOR_CARE_MODE_START_TIME_FIELD_NUMBER: _ClassVar[int]
    AC_ENERGY_SAVING_OPEN_FIELD_NUMBER: _ClassVar[int]
    MULTI_BP_CHG_DSG_MODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_5P8_CHG_HAL_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_HAL_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    errcode: int
    pow_in_sum_w: float
    pow_out_sum_w: float
    lcd_light: int
    energy_backup_state: int
    energy_backup_en: int
    energy_backup_start_soc: int
    pow_get_qcusb1: float
    pow_get_qcusb2: float
    pow_get_typec1: float
    pow_get_typec2: float
    flow_info_qcusb1: int
    flow_info_qcusb2: int
    flow_info_typec1: int
    flow_info_typec2: int
    dev_standby_time: int
    screen_off_time: int
    ac_standby_time: int
    dc_standby_time: int
    ac_always_on_mini_soc: int
    xboost_en: int
    pcs_fan_level: int
    flow_info_pv_h: int
    flow_info_pv_l: int
    flow_info_12v: int
    flow_info_24v: int
    pow_get_pv_h: float
    pow_get_pv_l: float
    pow_get_12v: float
    pow_get_24v: float
    plug_in_info_pv_h_flag: int
    plug_in_info_pv_h_type: int
    plug_in_info_pv_l_flag: int
    plug_in_info_pv_l_type: int
    flow_info_ac2dc: int
    flow_info_dc2ac: int
    flow_info_ac_in: int
    flow_info_ac_hv_out: int
    flow_info_ac_lv_out: int
    flow_info_5p8_in: int
    flow_info_5p8_out: int
    pow_get_llc: float
    pow_get_ac: float
    pow_get_ac_in: float
    pow_get_ac_hv_out: float
    pow_get_ac_lv_out: float
    pow_get_ac_lv_tt30_out: float
    pow_get_5p8: float
    plug_in_info_ac_in_flag: int
    plug_in_info_ac_in_feq: int
    plug_in_info_5p8_flag: int
    plug_in_info_5p8_type: int
    plug_in_info_5p8_detail: int
    current_time_task_v2_item: DP3TimeTaskItemV2
    utc_timezone: int
    utc_timezone_id: str
    utc_set_mode: int
    bms_err_code: int
    output_power_off_memory: int
    flow_info_bms_dsg: int
    flow_info_bms_chg: int
    flow_info_4p8_1_in: int
    flow_info_4p8_1_out: int
    flow_info_4p8_2_in: int
    flow_info_4p8_2_out: int
    pow_get_bms: float
    pow_get_4p8_1: float
    pow_get_4p8_2: float
    plug_in_info_4p8_1_in_flag: int
    plug_in_info_4p8_1_type: int
    plug_in_info_4p8_1_detail: int
    plug_in_info_4p8_2_in_flag: int
    plug_in_info_4p8_2_type: int
    plug_in_info_4p8_2_detail: int
    plug_in_info_pv_l_charger_flag: int
    plug_in_info_pv_h_charger_flag: int
    plug_in_info_pv_l_dc_amp_max: int
    plug_in_info_pv_h_dc_amp_max: int
    fast_charge_switch: int
    plug_in_info_4p8_1_dsg_chg_type: int
    plug_in_info_4p8_1_resv: DP3ResvInfo
    plug_in_info_4p8_1_sn: str
    plug_in_info_4p8_1_firm_ver: int
    plug_in_info_4p8_2_dsg_chg_type: int
    plug_in_info_4p8_2_resv: DP3ResvInfo
    plug_in_info_4p8_2_sn: str
    plug_in_info_4p8_2_firm_ver: int
    plug_in_info_5p8_dsg_chg: int
    plug_in_info_5p8_resv: DP3ResvInfo
    plug_in_info_5p8_sn: str
    plug_in_info_5p8_firm_ver: int
    en_beep: int
    llc_GFCI_flag: int
    plug_in_info_ac_charger_flag: int
    plug_in_info_5p8_charger_flag: int
    plug_in_info_5p8_run_state: int
    plug_in_info_4p8_1_charger_flag: int
    plug_in_info_4p8_1_run_state: int
    plug_in_info_4p8_2_charger_flag: int
    plug_in_info_4p8_2_run_state: int
    plug_in_info_ac_in_chg_pow_max: int
    plug_in_info_5p8_chg_pow_max: int
    ac_out_freq: int
    dev_sleep_state: int
    pd_err_code: int
    llc_err_code: int
    mppt_err_code: int
    plug_in_info_5p8_err_code: int
    plug_in_info_4p8_1_err_code: int
    plug_in_info_4p8_2_err_code: int
    pcs_fan_err_flag: int
    llc_hv_lv_flag: int
    llc_inv_err_code: int
    plug_in_info_pv_h_chg_vol_max: int
    plug_in_info_pv_l_chg_vol_max: int
    plug_in_info_pv_l_chg_amp_max: int
    plug_in_info_pv_h_chg_amp_max: int
    plug_in_info_5p8_dsg_pow_max: int
    plug_in_info_ac_out_dsg_pow_max: int
    bms_batt_soc: float
    bms_batt_soh: float
    bms_design_cap: int
    bms_dsg_rem_time: int
    bms_chg_rem_time: int
    bms_min_cell_temp: int
    bms_max_cell_temp: int
    bms_min_mos_temp: int
    bms_max_mos_temp: int
    cms_batt_soc: float
    cms_batt_soh: float
    cms_dsg_rem_time: int
    cms_chg_rem_time: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    cms_oil_on_soc: int
    cms_oil_off_soc: int
    cms_oil_self_start: int
    cms_bms_run_state: int
    bms_chg_dsg_state: int
    cms_chg_dsg_state: int
    ac_hv_always_on: int
    ac_lv_always_on: int
    time_task_conflict_flag: int
    time_task_change_cnt: int
    ble_standby_time: int
    generator_pv_hybrid_mode_open: int
    generator_pv_hybrid_mode_soc_max: int
    generator_care_mode_open: int
    generator_care_mode_start_time: int
    ac_energy_saving_open: int
    multi_bp_chg_dsg_mode: int
    plug_in_info_5p8_chg_hal_pow_max: int
    plug_in_info_ac_in_chg_hal_pow_max: int
    def __init__(self, errcode: int | None = ..., pow_in_sum_w: float | None = ..., pow_out_sum_w: float | None = ..., lcd_light: int | None = ..., energy_backup_state: int | None = ..., energy_backup_en: int | None = ..., energy_backup_start_soc: int | None = ..., pow_get_qcusb1: float | None = ..., pow_get_qcusb2: float | None = ..., pow_get_typec1: float | None = ..., pow_get_typec2: float | None = ..., flow_info_qcusb1: int | None = ..., flow_info_qcusb2: int | None = ..., flow_info_typec1: int | None = ..., flow_info_typec2: int | None = ..., dev_standby_time: int | None = ..., screen_off_time: int | None = ..., ac_standby_time: int | None = ..., dc_standby_time: int | None = ..., ac_always_on_mini_soc: int | None = ..., xboost_en: int | None = ..., pcs_fan_level: int | None = ..., flow_info_pv_h: int | None = ..., flow_info_pv_l: int | None = ..., flow_info_12v: int | None = ..., flow_info_24v: int | None = ..., pow_get_pv_h: float | None = ..., pow_get_pv_l: float | None = ..., pow_get_12v: float | None = ..., pow_get_24v: float | None = ..., plug_in_info_pv_h_flag: int | None = ..., plug_in_info_pv_h_type: int | None = ..., plug_in_info_pv_l_flag: int | None = ..., plug_in_info_pv_l_type: int | None = ..., flow_info_ac2dc: int | None = ..., flow_info_dc2ac: int | None = ..., flow_info_ac_in: int | None = ..., flow_info_ac_hv_out: int | None = ..., flow_info_ac_lv_out: int | None = ..., flow_info_5p8_in: int | None = ..., flow_info_5p8_out: int | None = ..., pow_get_llc: float | None = ..., pow_get_ac: float | None = ..., pow_get_ac_in: float | None = ..., pow_get_ac_hv_out: float | None = ..., pow_get_ac_lv_out: float | None = ..., pow_get_ac_lv_tt30_out: float | None = ..., pow_get_5p8: float | None = ..., plug_in_info_ac_in_flag: int | None = ..., plug_in_info_ac_in_feq: int | None = ..., plug_in_info_5p8_flag: int | None = ..., plug_in_info_5p8_type: int | None = ..., plug_in_info_5p8_detail: int | None = ..., current_time_task_v2_item: DP3TimeTaskItemV2 | _Mapping | None = ..., utc_timezone: int | None = ..., utc_timezone_id: str | None = ..., utc_set_mode: int | None = ..., bms_err_code: int | None = ..., output_power_off_memory: int | None = ..., flow_info_bms_dsg: int | None = ..., flow_info_bms_chg: int | None = ..., flow_info_4p8_1_in: int | None = ..., flow_info_4p8_1_out: int | None = ..., flow_info_4p8_2_in: int | None = ..., flow_info_4p8_2_out: int | None = ..., pow_get_bms: float | None = ..., pow_get_4p8_1: float | None = ..., pow_get_4p8_2: float | None = ..., plug_in_info_4p8_1_in_flag: int | None = ..., plug_in_info_4p8_1_type: int | None = ..., plug_in_info_4p8_1_detail: int | None = ..., plug_in_info_4p8_2_in_flag: int | None = ..., plug_in_info_4p8_2_type: int | None = ..., plug_in_info_4p8_2_detail: int | None = ..., plug_in_info_pv_l_charger_flag: int | None = ..., plug_in_info_pv_h_charger_flag: int | None = ..., plug_in_info_pv_l_dc_amp_max: int | None = ..., plug_in_info_pv_h_dc_amp_max: int | None = ..., fast_charge_switch: int | None = ..., plug_in_info_4p8_1_dsg_chg_type: int | None = ..., plug_in_info_4p8_1_resv: DP3ResvInfo | _Mapping | None = ..., plug_in_info_4p8_1_sn: str | None = ..., plug_in_info_4p8_1_firm_ver: int | None = ..., plug_in_info_4p8_2_dsg_chg_type: int | None = ..., plug_in_info_4p8_2_resv: DP3ResvInfo | _Mapping | None = ..., plug_in_info_4p8_2_sn: str | None = ..., plug_in_info_4p8_2_firm_ver: int | None = ..., plug_in_info_5p8_dsg_chg: int | None = ..., plug_in_info_5p8_resv: DP3ResvInfo | _Mapping | None = ..., plug_in_info_5p8_sn: str | None = ..., plug_in_info_5p8_firm_ver: int | None = ..., en_beep: int | None = ..., llc_GFCI_flag: int | None = ..., plug_in_info_ac_charger_flag: int | None = ..., plug_in_info_5p8_charger_flag: int | None = ..., plug_in_info_5p8_run_state: int | None = ..., plug_in_info_4p8_1_charger_flag: int | None = ..., plug_in_info_4p8_1_run_state: int | None = ..., plug_in_info_4p8_2_charger_flag: int | None = ..., plug_in_info_4p8_2_run_state: int | None = ..., plug_in_info_ac_in_chg_pow_max: int | None = ..., plug_in_info_5p8_chg_pow_max: int | None = ..., ac_out_freq: int | None = ..., dev_sleep_state: int | None = ..., pd_err_code: int | None = ..., llc_err_code: int | None = ..., mppt_err_code: int | None = ..., plug_in_info_5p8_err_code: int | None = ..., plug_in_info_4p8_1_err_code: int | None = ..., plug_in_info_4p8_2_err_code: int | None = ..., pcs_fan_err_flag: int | None = ..., llc_hv_lv_flag: int | None = ..., llc_inv_err_code: int | None = ..., plug_in_info_pv_h_chg_vol_max: int | None = ..., plug_in_info_pv_l_chg_vol_max: int | None = ..., plug_in_info_pv_l_chg_amp_max: int | None = ..., plug_in_info_pv_h_chg_amp_max: int | None = ..., plug_in_info_5p8_dsg_pow_max: int | None = ..., plug_in_info_ac_out_dsg_pow_max: int | None = ..., bms_batt_soc: float | None = ..., bms_batt_soh: float | None = ..., bms_design_cap: int | None = ..., bms_dsg_rem_time: int | None = ..., bms_chg_rem_time: int | None = ..., bms_min_cell_temp: int | None = ..., bms_max_cell_temp: int | None = ..., bms_min_mos_temp: int | None = ..., bms_max_mos_temp: int | None = ..., cms_batt_soc: float | None = ..., cms_batt_soh: float | None = ..., cms_dsg_rem_time: int | None = ..., cms_chg_rem_time: int | None = ..., cms_max_chg_soc: int | None = ..., cms_min_dsg_soc: int | None = ..., cms_oil_on_soc: int | None = ..., cms_oil_off_soc: int | None = ..., cms_oil_self_start: int | None = ..., cms_bms_run_state: int | None = ..., bms_chg_dsg_state: int | None = ..., cms_chg_dsg_state: int | None = ..., ac_hv_always_on: int | None = ..., ac_lv_always_on: int | None = ..., time_task_conflict_flag: int | None = ..., time_task_change_cnt: int | None = ..., ble_standby_time: int | None = ..., generator_pv_hybrid_mode_open: int | None = ..., generator_pv_hybrid_mode_soc_max: int | None = ..., generator_care_mode_open: int | None = ..., generator_care_mode_start_time: int | None = ..., ac_energy_saving_open: int | None = ..., multi_bp_chg_dsg_mode: int | None = ..., plug_in_info_5p8_chg_hal_pow_max: int | None = ..., plug_in_info_ac_in_chg_hal_pow_max: int | None = ...) -> None: ...

class DP3ResvInfo(_message.Message):
    __slots__ = ("resv_info",)
    RESV_INFO_FIELD_NUMBER: _ClassVar[int]
    resv_info: _containers.RepeatedScalarFieldContainer[int]
    def __init__(self, resv_info: _Iterable[int] | None = ...) -> None: ...

class DP3CMSStatus1(_message.Message):
    __slots__ = ("ac_out_freq", "bms_is_conn_state", "cms_batt_soc", "cms_batt_vol_mv", "cms_chg_dsg_state", "cms_chg_rem_time", "cms_chg_req_amp", "cms_dsg_rem_time", "cms_max_chg_soc", "cms_min_dsg_soc", "cms_oil_off_soc", "cms_status_misc1", "cms_status_misc2", "cms_status_misc3", "cms_status_misc4", "cms_status_misc5", "cms_status_misc6", "cms_status_misc7", "cms_status_misc8", "cms_status_misc9", "cms_status_misc10", "cms_status_misc11", "cms_status_misc12")
    CMS_STATUS_MISC1_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC2_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC3_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_VOL_MV_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_AMP_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC4_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC5_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC6_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    BMS_IS_CONN_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC7_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC8_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC9_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC10_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC11_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC12_FIELD_NUMBER: _ClassVar[int]
    CMS_OIL_OFF_SOC_FIELD_NUMBER: _ClassVar[int]
    cms_status_misc1: int
    cms_status_misc2: int
    cms_status_misc3: int
    cms_batt_vol_mv: int
    cms_chg_req_amp: int
    cms_status_misc4: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    ac_out_freq: int
    cms_status_misc5: int
    cms_status_misc6: int
    cms_chg_rem_time: int
    cms_dsg_rem_time: int
    cms_chg_dsg_state: int
    cms_batt_soc: float
    bms_is_conn_state: _containers.RepeatedScalarFieldContainer[int]
    cms_status_misc7: int
    cms_status_misc8: int
    cms_status_misc9: int
    cms_status_misc10: int
    cms_status_misc11: int
    cms_status_misc12: int
    cms_oil_off_soc: int
    def __init__(self, cms_status_misc1: int | None = ..., cms_status_misc2: int | None = ..., cms_status_misc3: int | None = ..., cms_batt_vol_mv: int | None = ..., cms_chg_req_amp: int | None = ..., cms_status_misc4: int | None = ..., cms_max_chg_soc: int | None = ..., cms_min_dsg_soc: int | None = ..., ac_out_freq: int | None = ..., cms_status_misc5: int | None = ..., cms_status_misc6: int | None = ..., cms_chg_rem_time: int | None = ..., cms_dsg_rem_time: int | None = ..., cms_chg_dsg_state: int | None = ..., cms_batt_soc: float | None = ..., bms_is_conn_state: _Iterable[int] | None = ..., cms_status_misc7: int | None = ..., cms_status_misc8: int | None = ..., cms_status_misc9: int | None = ..., cms_status_misc10: int | None = ..., cms_status_misc11: int | None = ..., cms_status_misc12: int | None = ..., cms_oil_off_soc: int | None = ...) -> None: ...

class DP3CMSStatus2(_message.Message):
    __slots__ = ("cms_status_misc13", "cms_status_misc14", "cms_status_misc15", "cms_status_misc16", "cms_status_misc17")
    CMS_STATUS_MISC13_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC14_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC15_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC16_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC17_FIELD_NUMBER: _ClassVar[int]
    cms_status_misc13: int
    cms_status_misc14: int
    cms_status_misc15: int
    cms_status_misc16: int
    cms_status_misc17: int
    def __init__(self, cms_status_misc13: int | None = ..., cms_status_misc14: int | None = ..., cms_status_misc15: int | None = ..., cms_status_misc16: int | None = ..., cms_status_misc17: int | None = ...) -> None: ...

class DP3CMSHeartBeatReport(_message.Message):
    __slots__ = ("msg32_2_1", "msg32_2_2")
    MSG32_2_1_FIELD_NUMBER: _ClassVar[int]
    MSG32_2_2_FIELD_NUMBER: _ClassVar[int]
    msg32_2_1: DP3CMSStatus1
    msg32_2_2: DP3CMSStatus2
    def __init__(self, msg32_2_1: DP3CMSStatus1 | _Mapping | None = ..., msg32_2_2: DP3CMSStatus2 | _Mapping | None = ...) -> None: ...

class DP3RuntimePropertyReport(_message.Message):
    __slots__ = ("report_timestamp", "unknown2_f22", "unknown5_f22")
    REPORT_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN2_F22_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN5_F22_FIELD_NUMBER: _ClassVar[int]
    report_timestamp: int
    unknown2_f22: float
    unknown5_f22: int
    def __init__(self, report_timestamp: int | None = ..., unknown2_f22: float | None = ..., unknown5_f22: int | None = ...) -> None: ...

class DP3DisplayPropertyReport(_message.Message):
    __slots__ = ("report_timestamp", "unknown2_f23", "unknown5_f23")
    REPORT_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN2_F23_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN5_F23_FIELD_NUMBER: _ClassVar[int]
    report_timestamp: int
    unknown2_f23: float
    unknown5_f23: int
    def __init__(self, report_timestamp: int | None = ..., unknown2_f23: float | None = ..., unknown5_f23: int | None = ...) -> None: ...

class DP3SetCommand(_message.Message):
    __slots__ = ("acEnergySavingOpen", "acStandbyTime", "cfgDc12vOutOpen", "cfgHvAcOutOpen", "cfgLvAcOutOpen", "cfgPowerOff", "cmsMaxChgSoc", "cmsMinDsgSoc", "cmsOilOffSoc", "cmsOilOnSoc", "cmsOilSelfStart", "dcStandbyTime", "devStandbyTime", "enBeep", "lcdLight", "llc_GFCIFlag", "lowDischargeLimitCmd", "multiBpChgDsgMode", "plugInInfoAcInChgPowMax", "plugInInfoPvHDcAmpMax", "plugInInfoPvLDcAmpMax", "plugInInfo_5p8ChgPowMax", "screenOffTime", "unknown167", "xboostEn")
    CFGPOWEROFF_FIELD_NUMBER: _ClassVar[int]
    ENBEEP_FIELD_NUMBER: _ClassVar[int]
    ACSTANDBYTIME_FIELD_NUMBER: _ClassVar[int]
    DCSTANDBYTIME_FIELD_NUMBER: _ClassVar[int]
    SCREENOFFTIME_FIELD_NUMBER: _ClassVar[int]
    DEVSTANDBYTIME_FIELD_NUMBER: _ClassVar[int]
    LCDLIGHT_FIELD_NUMBER: _ClassVar[int]
    CFGHVACOUTOPEN_FIELD_NUMBER: _ClassVar[int]
    CFGLVACOUTOPEN_FIELD_NUMBER: _ClassVar[int]
    CFGDC12VOUTOPEN_FIELD_NUMBER: _ClassVar[int]
    XBOOSTEN_FIELD_NUMBER: _ClassVar[int]
    CMSMAXCHGSOC_FIELD_NUMBER: _ClassVar[int]
    CMSMINDSGSOC_FIELD_NUMBER: _ClassVar[int]
    PLUGININFOPVLDCAMPMAX_FIELD_NUMBER: _ClassVar[int]
    PLUGININFOPVHDCAMPMAX_FIELD_NUMBER: _ClassVar[int]
    PLUGININFOACINCHGPOWMAX_FIELD_NUMBER: _ClassVar[int]
    PLUGININFO_5P8CHGPOWMAX_FIELD_NUMBER: _ClassVar[int]
    CMSOILSELFSTART_FIELD_NUMBER: _ClassVar[int]
    CMSOILONSOC_FIELD_NUMBER: _ClassVar[int]
    CMSOILOFFSOC_FIELD_NUMBER: _ClassVar[int]
    LLC_GFCIFLAG_FIELD_NUMBER: _ClassVar[int]
    ACENERGYSAVINGOPEN_FIELD_NUMBER: _ClassVar[int]
    MULTIBPCHGDSGMODE_FIELD_NUMBER: _ClassVar[int]
    LOWDISCHARGELIMITCMD_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN167_FIELD_NUMBER: _ClassVar[int]
    cfgPowerOff: int
    enBeep: int
    acStandbyTime: int
    dcStandbyTime: int
    screenOffTime: int
    devStandbyTime: int
    lcdLight: int
    cfgHvAcOutOpen: int
    cfgLvAcOutOpen: int
    cfgDc12vOutOpen: int
    xboostEn: int
    cmsMaxChgSoc: int
    cmsMinDsgSoc: int
    plugInInfoPvLDcAmpMax: int
    plugInInfoPvHDcAmpMax: int
    plugInInfoAcInChgPowMax: int
    plugInInfo_5p8ChgPowMax: int
    cmsOilSelfStart: int
    cmsOilOnSoc: int
    cmsOilOffSoc: int
    llc_GFCIFlag: int
    acEnergySavingOpen: int
    multiBpChgDsgMode: int
    lowDischargeLimitCmd: int
    unknown167: int
    def __init__(self, cfgPowerOff: int | None = ..., enBeep: int | None = ..., acStandbyTime: int | None = ..., dcStandbyTime: int | None = ..., screenOffTime: int | None = ..., devStandbyTime: int | None = ..., lcdLight: int | None = ..., cfgHvAcOutOpen: int | None = ..., cfgLvAcOutOpen: int | None = ..., cfgDc12vOutOpen: int | None = ..., xboostEn: int | None = ..., cmsMaxChgSoc: int | None = ..., cmsMinDsgSoc: int | None = ..., plugInInfoPvLDcAmpMax: int | None = ..., plugInInfoPvHDcAmpMax: int | None = ..., plugInInfoAcInChgPowMax: int | None = ..., plugInInfo_5p8ChgPowMax: int | None = ..., cmsOilSelfStart: int | None = ..., cmsOilOnSoc: int | None = ..., cmsOilOffSoc: int | None = ..., llc_GFCIFlag: int | None = ..., acEnergySavingOpen: int | None = ..., multiBpChgDsgMode: int | None = ..., lowDischargeLimitCmd: int | None = ..., unknown167: int | None = ...) -> None: ...

class DP3SetReply(_message.Message):
    __slots__ = ("acEnergySavingOpen", "acStandbyTime", "actionId", "cfgDc12vOutOpen", "cfgHvAcOutOpen", "cfgLvAcOutOpen", "cfgPowerOff", "cmsMaxChgSoc", "cmsMinDsgSoc", "cmsOilOffSoc", "cmsOilOnSoc", "cmsOilSelfStart", "configOk", "dcStandbyTime", "devStandbyTime", "enBeep", "lcdLight", "llc_GFCIFlag", "lowDischargeLimitCmd", "multiBpChgDsgMode", "plugInInfoAcInChgPowMax", "plugInInfoPvHDcAmpMax", "plugInInfoPvLDcAmpMax", "plugInInfo_5p8ChgPowMax", "screenOffTime", "unknown167", "xboostEn")
    ACTIONID_FIELD_NUMBER: _ClassVar[int]
    CONFIGOK_FIELD_NUMBER: _ClassVar[int]
    CFGPOWEROFF_FIELD_NUMBER: _ClassVar[int]
    ENBEEP_FIELD_NUMBER: _ClassVar[int]
    ACSTANDBYTIME_FIELD_NUMBER: _ClassVar[int]
    DCSTANDBYTIME_FIELD_NUMBER: _ClassVar[int]
    SCREENOFFTIME_FIELD_NUMBER: _ClassVar[int]
    DEVSTANDBYTIME_FIELD_NUMBER: _ClassVar[int]
    LCDLIGHT_FIELD_NUMBER: _ClassVar[int]
    CFGHVACOUTOPEN_FIELD_NUMBER: _ClassVar[int]
    CFGLVACOUTOPEN_FIELD_NUMBER: _ClassVar[int]
    CFGDC12VOUTOPEN_FIELD_NUMBER: _ClassVar[int]
    XBOOSTEN_FIELD_NUMBER: _ClassVar[int]
    CMSMAXCHGSOC_FIELD_NUMBER: _ClassVar[int]
    CMSMINDSGSOC_FIELD_NUMBER: _ClassVar[int]
    PLUGININFOPVLDCAMPMAX_FIELD_NUMBER: _ClassVar[int]
    PLUGININFOPVHDCAMPMAX_FIELD_NUMBER: _ClassVar[int]
    PLUGININFOACINCHGPOWMAX_FIELD_NUMBER: _ClassVar[int]
    PLUGININFO_5P8CHGPOWMAX_FIELD_NUMBER: _ClassVar[int]
    CMSOILSELFSTART_FIELD_NUMBER: _ClassVar[int]
    CMSOILONSOC_FIELD_NUMBER: _ClassVar[int]
    CMSOILOFFSOC_FIELD_NUMBER: _ClassVar[int]
    LLC_GFCIFLAG_FIELD_NUMBER: _ClassVar[int]
    ACENERGYSAVINGOPEN_FIELD_NUMBER: _ClassVar[int]
    MULTIBPCHGDSGMODE_FIELD_NUMBER: _ClassVar[int]
    LOWDISCHARGELIMITCMD_FIELD_NUMBER: _ClassVar[int]
    UNKNOWN167_FIELD_NUMBER: _ClassVar[int]
    actionId: int
    configOk: bool
    cfgPowerOff: int
    enBeep: int
    acStandbyTime: int
    dcStandbyTime: int
    screenOffTime: int
    devStandbyTime: int
    lcdLight: int
    cfgHvAcOutOpen: int
    cfgLvAcOutOpen: int
    cfgDc12vOutOpen: int
    xboostEn: int
    cmsMaxChgSoc: int
    cmsMinDsgSoc: int
    plugInInfoPvLDcAmpMax: int
    plugInInfoPvHDcAmpMax: int
    plugInInfoAcInChgPowMax: int
    plugInInfo_5p8ChgPowMax: int
    cmsOilSelfStart: int
    cmsOilOnSoc: int
    cmsOilOffSoc: int
    llc_GFCIFlag: int
    acEnergySavingOpen: int
    multiBpChgDsgMode: int
    lowDischargeLimitCmd: int
    unknown167: int
    def __init__(self, actionId: int | None = ..., configOk: bool | None = ..., cfgPowerOff: int | None = ..., enBeep: int | None = ..., acStandbyTime: int | None = ..., dcStandbyTime: int | None = ..., screenOffTime: int | None = ..., devStandbyTime: int | None = ..., lcdLight: int | None = ..., cfgHvAcOutOpen: int | None = ..., cfgLvAcOutOpen: int | None = ..., cfgDc12vOutOpen: int | None = ..., xboostEn: int | None = ..., cmsMaxChgSoc: int | None = ..., cmsMinDsgSoc: int | None = ..., plugInInfoPvLDcAmpMax: int | None = ..., plugInInfoPvHDcAmpMax: int | None = ..., plugInInfoAcInChgPowMax: int | None = ..., plugInInfo_5p8ChgPowMax: int | None = ..., cmsOilSelfStart: int | None = ..., cmsOilOnSoc: int | None = ..., cmsOilOffSoc: int | None = ..., llc_GFCIFlag: int | None = ..., acEnergySavingOpen: int | None = ..., multiBpChgDsgMode: int | None = ..., lowDischargeLimitCmd: int | None = ..., unknown167: int | None = ...) -> None: ...

class DP3SetValue(_message.Message):
    __slots__ = ("value", "value2")
    VALUE_FIELD_NUMBER: _ClassVar[int]
    VALUE2_FIELD_NUMBER: _ClassVar[int]
    value: int
    value2: int
    def __init__(self, value: int | None = ..., value2: int | None = ...) -> None: ...

class DP3SetMessage(_message.Message):
    __slots__ = ("header",)
    HEADER_FIELD_NUMBER: _ClassVar[int]
    header: DP3Header
    def __init__(self, header: DP3Header | _Mapping | None = ...) -> None: ...

class DP3HeaderMessage(_message.Message):
    __slots__ = ("header",)
    HEADER_FIELD_NUMBER: _ClassVar[int]
    header: _containers.RepeatedCompositeFieldContainer[DP3Header]
    def __init__(self, header: _Iterable[DP3Header | _Mapping] | None = ...) -> None: ...

class DP3SendHeaderMsgLegacy(_message.Message):
    __slots__ = ("msg",)
    MSG_FIELD_NUMBER: _ClassVar[int]
    msg: DP3Header
    def __init__(self, msg: DP3Header | _Mapping | None = ...) -> None: ...

class DP3BMSHeartBeatReport(_message.Message):
    __slots__ = ("accu_chg_cap", "accu_chg_energy", "accu_dsg_cap", "accu_dsg_energy", "act_soc", "afe_sys_status", "all_bms_fault", "all_err_code", "amp", "balance_cmd", "balance_state", "bms_alarm_state1", "bms_alarm_state2", "bms_fault", "bms_fault_state", "bms_heartbeat_ver", "bms_protect_state1", "bms_protect_state2", "bms_sn", "bq_sys_stat_reg", "calendar_soh", "cell_id", "cell_ntc_num", "cell_series_num", "cell_temp", "cell_vol", "chg_dsg_state", "cur_sensor_ntc_num", "cur_sensor_temp", "cycle_soh", "cycles", "design_cap", "diff_soc", "ecloud_ocv", "env_ntc_num", "env_temp", "err_code", "f32_show_soc", "full_cap", "heatfilm_ntc_num", "heatfilm_temp", "hw_ver", "input_watts", "max_cell_temp", "max_cell_vol", "max_cur_sensor_temp", "max_env_temp", "max_heatfilm_temp", "max_mos_temp", "max_vol_diff", "mcu_pin_in_status", "mcu_pin_out_status", "min_cell_temp", "min_cell_vol", "min_cur_sensor_temp", "min_env_temp", "min_heatfilm_temp", "min_mos_temp", "mos_ntc_num", "mos_state", "mos_temp", "num", "open_bms_flag", "output_watts", "pack_sn", "product_detail", "product_type", "real_soh", "remain_balance_time", "remain_cap", "remain_time", "soc", "soh", "sys_loader_ver", "sys_state", "sys_ver", "tag_chg_amp", "target_soc", "temp", "type", "vol", "water_in_flag")
    NUM_FIELD_NUMBER: _ClassVar[int]
    TYPE_FIELD_NUMBER: _ClassVar[int]
    CELL_ID_FIELD_NUMBER: _ClassVar[int]
    ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    SYS_VER_FIELD_NUMBER: _ClassVar[int]
    SOC_FIELD_NUMBER: _ClassVar[int]
    VOL_FIELD_NUMBER: _ClassVar[int]
    AMP_FIELD_NUMBER: _ClassVar[int]
    TEMP_FIELD_NUMBER: _ClassVar[int]
    OPEN_BMS_FLAG_FIELD_NUMBER: _ClassVar[int]
    DESIGN_CAP_FIELD_NUMBER: _ClassVar[int]
    REMAIN_CAP_FIELD_NUMBER: _ClassVar[int]
    FULL_CAP_FIELD_NUMBER: _ClassVar[int]
    CYCLES_FIELD_NUMBER: _ClassVar[int]
    SOH_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_FAULT_FIELD_NUMBER: _ClassVar[int]
    BQ_SYS_STAT_REG_FIELD_NUMBER: _ClassVar[int]
    TAG_CHG_AMP_FIELD_NUMBER: _ClassVar[int]
    F32_SHOW_SOC_FIELD_NUMBER: _ClassVar[int]
    INPUT_WATTS_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_WATTS_FIELD_NUMBER: _ClassVar[int]
    REMAIN_TIME_FIELD_NUMBER: _ClassVar[int]
    MOS_STATE_FIELD_NUMBER: _ClassVar[int]
    BALANCE_STATE_FIELD_NUMBER: _ClassVar[int]
    MAX_VOL_DIFF_FIELD_NUMBER: _ClassVar[int]
    CELL_SERIES_NUM_FIELD_NUMBER: _ClassVar[int]
    CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    CELL_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    HW_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_HEARTBEAT_VER_FIELD_NUMBER: _ClassVar[int]
    ECLOUD_OCV_FIELD_NUMBER: _ClassVar[int]
    BMS_SN_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_TYPE_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_DETAIL_FIELD_NUMBER: _ClassVar[int]
    ACT_SOC_FIELD_NUMBER: _ClassVar[int]
    DIFF_SOC_FIELD_NUMBER: _ClassVar[int]
    TARGET_SOC_FIELD_NUMBER: _ClassVar[int]
    SYS_LOADER_VER_FIELD_NUMBER: _ClassVar[int]
    SYS_STATE_FIELD_NUMBER: _ClassVar[int]
    CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    ALL_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    ALL_BMS_FAULT_FIELD_NUMBER: _ClassVar[int]
    ACCU_CHG_CAP_FIELD_NUMBER: _ClassVar[int]
    ACCU_DSG_CAP_FIELD_NUMBER: _ClassVar[int]
    REAL_SOH_FIELD_NUMBER: _ClassVar[int]
    CALENDAR_SOH_FIELD_NUMBER: _ClassVar[int]
    CYCLE_SOH_FIELD_NUMBER: _ClassVar[int]
    MOS_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    ENV_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    HEATFILM_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    CUR_SENSOR_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    BALANCE_CMD_FIELD_NUMBER: _ClassVar[int]
    REMAIN_BALANCE_TIME_FIELD_NUMBER: _ClassVar[int]
    AFE_SYS_STATUS_FIELD_NUMBER: _ClassVar[int]
    MCU_PIN_IN_STATUS_FIELD_NUMBER: _ClassVar[int]
    MCU_PIN_OUT_STATUS_FIELD_NUMBER: _ClassVar[int]
    BMS_ALARM_STATE1_FIELD_NUMBER: _ClassVar[int]
    BMS_ALARM_STATE2_FIELD_NUMBER: _ClassVar[int]
    BMS_PROTECT_STATE1_FIELD_NUMBER: _ClassVar[int]
    BMS_PROTECT_STATE2_FIELD_NUMBER: _ClassVar[int]
    BMS_FAULT_STATE_FIELD_NUMBER: _ClassVar[int]
    ACCU_CHG_ENERGY_FIELD_NUMBER: _ClassVar[int]
    ACCU_DSG_ENERGY_FIELD_NUMBER: _ClassVar[int]
    PACK_SN_FIELD_NUMBER: _ClassVar[int]
    WATER_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    num: int
    type: int
    cell_id: int
    err_code: int
    sys_ver: int
    soc: int
    vol: int
    amp: int
    temp: int
    open_bms_flag: int
    design_cap: int
    remain_cap: int
    full_cap: int
    cycles: int
    soh: int
    max_cell_vol: int
    min_cell_vol: int
    max_cell_temp: int
    min_cell_temp: int
    max_mos_temp: int
    min_mos_temp: int
    bms_fault: int
    bq_sys_stat_reg: int
    tag_chg_amp: int
    f32_show_soc: float
    input_watts: int
    output_watts: int
    remain_time: int
    mos_state: int
    balance_state: int
    max_vol_diff: int
    cell_series_num: int
    cell_vol: _containers.RepeatedScalarFieldContainer[int]
    cell_ntc_num: int
    cell_temp: _containers.RepeatedScalarFieldContainer[int]
    hw_ver: str
    bms_heartbeat_ver: int
    ecloud_ocv: int
    bms_sn: str
    product_type: int
    product_detail: int
    act_soc: float
    diff_soc: float
    target_soc: float
    sys_loader_ver: int
    sys_state: int
    chg_dsg_state: int
    all_err_code: int
    all_bms_fault: int
    accu_chg_cap: int
    accu_dsg_cap: int
    real_soh: float
    calendar_soh: float
    cycle_soh: float
    mos_ntc_num: int
    mos_temp: _containers.RepeatedScalarFieldContainer[int]
    env_ntc_num: int
    env_temp: _containers.RepeatedScalarFieldContainer[int]
    heatfilm_ntc_num: int
    heatfilm_temp: _containers.RepeatedScalarFieldContainer[int]
    cur_sensor_ntc_num: int
    cur_sensor_temp: _containers.RepeatedScalarFieldContainer[int]
    max_env_temp: int
    min_env_temp: int
    max_heatfilm_temp: int
    min_heatfilm_temp: int
    max_cur_sensor_temp: int
    min_cur_sensor_temp: int
    balance_cmd: int
    remain_balance_time: _containers.RepeatedScalarFieldContainer[int]
    afe_sys_status: int
    mcu_pin_in_status: int
    mcu_pin_out_status: int
    bms_alarm_state1: int
    bms_alarm_state2: int
    bms_protect_state1: int
    bms_protect_state2: int
    bms_fault_state: int
    accu_chg_energy: int
    accu_dsg_energy: int
    pack_sn: str
    water_in_flag: int
    def __init__(self, num: int | None = ..., type: int | None = ..., cell_id: int | None = ..., err_code: int | None = ..., sys_ver: int | None = ..., soc: int | None = ..., vol: int | None = ..., amp: int | None = ..., temp: int | None = ..., open_bms_flag: int | None = ..., design_cap: int | None = ..., remain_cap: int | None = ..., full_cap: int | None = ..., cycles: int | None = ..., soh: int | None = ..., max_cell_vol: int | None = ..., min_cell_vol: int | None = ..., max_cell_temp: int | None = ..., min_cell_temp: int | None = ..., max_mos_temp: int | None = ..., min_mos_temp: int | None = ..., bms_fault: int | None = ..., bq_sys_stat_reg: int | None = ..., tag_chg_amp: int | None = ..., f32_show_soc: float | None = ..., input_watts: int | None = ..., output_watts: int | None = ..., remain_time: int | None = ..., mos_state: int | None = ..., balance_state: int | None = ..., max_vol_diff: int | None = ..., cell_series_num: int | None = ..., cell_vol: _Iterable[int] | None = ..., cell_ntc_num: int | None = ..., cell_temp: _Iterable[int] | None = ..., hw_ver: str | None = ..., bms_heartbeat_ver: int | None = ..., ecloud_ocv: int | None = ..., bms_sn: str | None = ..., product_type: int | None = ..., product_detail: int | None = ..., act_soc: float | None = ..., diff_soc: float | None = ..., target_soc: float | None = ..., sys_loader_ver: int | None = ..., sys_state: int | None = ..., chg_dsg_state: int | None = ..., all_err_code: int | None = ..., all_bms_fault: int | None = ..., accu_chg_cap: int | None = ..., accu_dsg_cap: int | None = ..., real_soh: float | None = ..., calendar_soh: float | None = ..., cycle_soh: float | None = ..., mos_ntc_num: int | None = ..., mos_temp: _Iterable[int] | None = ..., env_ntc_num: int | None = ..., env_temp: _Iterable[int] | None = ..., heatfilm_ntc_num: int | None = ..., heatfilm_temp: _Iterable[int] | None = ..., cur_sensor_ntc_num: int | None = ..., cur_sensor_temp: _Iterable[int] | None = ..., max_env_temp: int | None = ..., min_env_temp: int | None = ..., max_heatfilm_temp: int | None = ..., min_heatfilm_temp: int | None = ..., max_cur_sensor_temp: int | None = ..., min_cur_sensor_temp: int | None = ..., balance_cmd: int | None = ..., remain_balance_time: _Iterable[int] | None = ..., afe_sys_status: int | None = ..., mcu_pin_in_status: int | None = ..., mcu_pin_out_status: int | None = ..., bms_alarm_state1: int | None = ..., bms_alarm_state2: int | None = ..., bms_protect_state1: int | None = ..., bms_protect_state2: int | None = ..., bms_fault_state: int | None = ..., accu_chg_energy: int | None = ..., accu_dsg_energy: int | None = ..., pack_sn: str | None = ..., water_in_flag: int | None = ...) -> None: ...
