from collections.abc import Iterable as _Iterable
from collections.abc import Mapping as _Mapping
from typing import ClassVar as _ClassVar

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers

DESCRIPTOR: _descriptor.FileDescriptor

class Delta3Header(_message.Message):
    __slots__ = ("ack_type", "check_type", "cmd_func", "cmd_id", "code", "d_dest", "d_src", "data_len", "dest", "device_sn", "enc_type", "is_ack", "is_queue", "is_rw_cmd", "module_sn", "need_ack", "payload_ver", "pdata", "product_id", "seq", "src", "time_snap", "version")
    PDATA_FIELD_NUMBER: _ClassVar[int]
    SRC_FIELD_NUMBER: _ClassVar[int]
    DEST_FIELD_NUMBER: _ClassVar[int]
    D_SRC_FIELD_NUMBER: _ClassVar[int]
    D_DEST_FIELD_NUMBER: _ClassVar[int]
    ENC_TYPE_FIELD_NUMBER: _ClassVar[int]
    CHECK_TYPE_FIELD_NUMBER: _ClassVar[int]
    CMD_FUNC_FIELD_NUMBER: _ClassVar[int]
    CMD_ID_FIELD_NUMBER: _ClassVar[int]
    DATA_LEN_FIELD_NUMBER: _ClassVar[int]
    NEED_ACK_FIELD_NUMBER: _ClassVar[int]
    IS_ACK_FIELD_NUMBER: _ClassVar[int]
    SEQ_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_ID_FIELD_NUMBER: _ClassVar[int]
    VERSION_FIELD_NUMBER: _ClassVar[int]
    PAYLOAD_VER_FIELD_NUMBER: _ClassVar[int]
    TIME_SNAP_FIELD_NUMBER: _ClassVar[int]
    IS_RW_CMD_FIELD_NUMBER: _ClassVar[int]
    IS_QUEUE_FIELD_NUMBER: _ClassVar[int]
    ACK_TYPE_FIELD_NUMBER: _ClassVar[int]
    CODE_FIELD_NUMBER: _ClassVar[int]
    FROM_FIELD_NUMBER: _ClassVar[int]
    MODULE_SN_FIELD_NUMBER: _ClassVar[int]
    DEVICE_SN_FIELD_NUMBER: _ClassVar[int]
    pdata: bytes
    src: int
    dest: int
    d_src: int
    d_dest: int
    enc_type: int
    check_type: int
    cmd_func: int
    cmd_id: int
    data_len: int
    need_ack: int
    is_ack: int
    seq: int
    product_id: int
    version: int
    payload_ver: int
    time_snap: int
    is_rw_cmd: int
    is_queue: int
    ack_type: int
    code: str
    module_sn: str
    device_sn: str
    def __init__(self, pdata: bytes | None = ..., src: int | None = ..., dest: int | None = ..., d_src: int | None = ..., d_dest: int | None = ..., enc_type: int | None = ..., check_type: int | None = ..., cmd_func: int | None = ..., cmd_id: int | None = ..., data_len: int | None = ..., need_ack: int | None = ..., is_ack: int | None = ..., seq: int | None = ..., product_id: int | None = ..., version: int | None = ..., payload_ver: int | None = ..., time_snap: int | None = ..., is_rw_cmd: int | None = ..., is_queue: int | None = ..., ack_type: int | None = ..., code: str | None = ..., module_sn: str | None = ..., device_sn: str | None = ..., **kwargs) -> None: ...

class Delta3SendHeaderMsg(_message.Message):
    __slots__ = ("msg",)
    MSG_FIELD_NUMBER: _ClassVar[int]
    msg: _containers.RepeatedCompositeFieldContainer[Delta3Header]
    def __init__(self, msg: _Iterable[Delta3Header | _Mapping] | None = ...) -> None: ...

class Delta3DisplayPropertyUpload(_message.Message):
    __slots__ = ("ac_always_on_flag", "ac_always_on_mini_soc", "ac_out_freq", "ac_standby_time", "backup_reverse_soc", "ban_bypass_en", "bms_batt_soc", "bms_batt_soh", "bms_chg_dsg_state", "bms_chg_rem_time", "bms_design_cap", "bms_dsg_rem_time", "bms_err_code", "bms_max_cell_temp", "bms_max_mos_temp", "bms_min_cell_temp", "bms_min_mos_temp", "cfg_ac_out_open", "cms_batt_soc", "cms_batt_soh", "cms_bms_run_state", "cms_chg_dsg_state", "cms_chg_rem_time", "cms_dsg_rem_time", "cms_max_chg_soc", "cms_min_dsg_soc", "dc_out_open", "dc_standby_time", "dev_sleep_state", "dev_standby_time", "en_beep", "energy_backup_en", "energy_backup_start_soc", "energy_strategy_operate_mode", "errcode", "flow_info_12v", "flow_info_ac2dc", "flow_info_ac_in", "flow_info_ac_out", "flow_info_bms_chg", "flow_info_bms_dsg", "flow_info_dc2ac", "flow_info_dcp2_in", "flow_info_dcp2_out", "flow_info_dcp_in", "flow_info_dcp_out", "flow_info_pv", "flow_info_qcusb1", "flow_info_qcusb2", "flow_info_typec1", "flow_info_typec2", "led_mode", "llc_hv_lv_flag", "llc_inv_err_code", "low_power_alarm", "mppt_err_code", "output_power_off_memory", "pcs_fan_level", "pd_err_code", "plug_in_info_ac_charger_flag", "plug_in_info_ac_in_chg_hal_pow_max", "plug_in_info_ac_in_chg_mode", "plug_in_info_ac_in_chg_pow_max", "plug_in_info_ac_in_feq", "plug_in_info_ac_in_flag", "plug_in_info_ac_out_dsg_pow_max", "plug_in_info_dcp2_charger_flag", "plug_in_info_dcp2_detail", "plug_in_info_dcp2_dsg_chg_type", "plug_in_info_dcp2_err_code", "plug_in_info_dcp2_firm_ver", "plug_in_info_dcp2_in_flag", "plug_in_info_dcp2_run_state", "plug_in_info_dcp2_sn", "plug_in_info_dcp2_type", "plug_in_info_dcp_charger_flag", "plug_in_info_dcp_detail", "plug_in_info_dcp_dsg_chg_type", "plug_in_info_dcp_err_code", "plug_in_info_dcp_firm_ver", "plug_in_info_dcp_in_flag", "plug_in_info_dcp_run_state", "plug_in_info_dcp_sn", "plug_in_info_dcp_type", "plug_in_info_pv_charger_flag", "plug_in_info_pv_chg_amp_max", "plug_in_info_pv_chg_vol_max", "plug_in_info_pv_dc_amp_max", "plug_in_info_pv_flag", "plug_in_info_pv_type", "pow_get_12v", "pow_get_ac", "pow_get_ac_in", "pow_get_ac_out", "pow_get_bms", "pow_get_dcp", "pow_get_dcp2", "pow_get_pv", "pow_get_qcusb1", "pow_get_qcusb2", "pow_get_typec1", "pow_get_typec2", "pow_in_sum_w", "pow_out_sum_w", "pv_chg_type", "screen_off_time", "self_powered_conflict_flag", "silence_chg_watt", "time_task_change_cnt", "time_task_conflict_flag", "tou_mode_conflict_flag", "ups_alram", "xboost_en")
    ERRCODE_FIELD_NUMBER: _ClassVar[int]
    POW_IN_SUM_W_FIELD_NUMBER: _ClassVar[int]
    POW_OUT_SUM_W_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_EN_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_START_SOC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_QCUSB1_FIELD_NUMBER: _ClassVar[int]
    POW_GET_QCUSB2_FIELD_NUMBER: _ClassVar[int]
    POW_GET_TYPEC1_FIELD_NUMBER: _ClassVar[int]
    POW_GET_TYPEC2_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_QCUSB1_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_QCUSB2_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_TYPEC1_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_TYPEC2_FIELD_NUMBER: _ClassVar[int]
    DEV_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    SCREEN_OFF_TIME_FIELD_NUMBER: _ClassVar[int]
    AC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    DC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    AC_ALWAYS_ON_FLAG_FIELD_NUMBER: _ClassVar[int]
    AC_ALWAYS_ON_MINI_SOC_FIELD_NUMBER: _ClassVar[int]
    XBOOST_EN_FIELD_NUMBER: _ClassVar[int]
    PCS_FAN_LEVEL_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_12V_FIELD_NUMBER: _ClassVar[int]
    POW_GET_12V_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC2DC_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_DC2AC_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC_IN_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_IN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_FEQ_FIELD_NUMBER: _ClassVar[int]
    DC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    CFG_AC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    POW_GET_DCP2_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_DCP2_IN_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_DCP2_OUT_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_DSG_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_DETAIL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_SN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    BAN_BYPASS_EN_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_POWER_OFF_MEMORY_FIELD_NUMBER: _ClassVar[int]
    PV_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_BMS_DSG_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_BMS_CHG_FIELD_NUMBER: _ClassVar[int]
    POW_GET_BMS_FIELD_NUMBER: _ClassVar[int]
    EN_BEEP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    DEV_SLEEP_STATE_FIELD_NUMBER: _ClassVar[int]
    PD_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    MPPT_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    LLC_HV_LV_FLAG_FIELD_NUMBER: _ClassVar[int]
    LLC_INV_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_DSG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOH_FIELD_NUMBER: _ClassVar[int]
    BMS_DESIGN_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOH_FIELD_NUMBER: _ClassVar[int]
    CMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_BMS_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    TIME_TASK_CONFLICT_FLAG_FIELD_NUMBER: _ClassVar[int]
    TIME_TASK_CHANGE_CNT_FIELD_NUMBER: _ClassVar[int]
    UPS_ALRAM_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    LED_MODE_FIELD_NUMBER: _ClassVar[int]
    LOW_POWER_ALARM_FIELD_NUMBER: _ClassVar[int]
    SILENCE_CHG_WATT_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_PV_FIELD_NUMBER: _ClassVar[int]
    POW_GET_PV_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_CHG_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_CHG_VOL_MAX_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_OUT_FIELD_NUMBER: _ClassVar[int]
    ENERGY_STRATEGY_OPERATE_MODE_FIELD_NUMBER: _ClassVar[int]
    SELF_POWERED_CONFLICT_FLAG_FIELD_NUMBER: _ClassVar[int]
    TOU_MODE_CONFLICT_FLAG_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_DCP_IN_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_DCP_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_DCP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_DETAIL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_DSG_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_SN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP2_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_MODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_HAL_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    BACKUP_REVERSE_SOC_FIELD_NUMBER: _ClassVar[int]
    errcode: int
    pow_in_sum_w: float
    pow_out_sum_w: float
    energy_backup_en: int
    energy_backup_start_soc: int
    pow_get_qcusb1: float
    pow_get_qcusb2: float
    pow_get_typec1: float
    pow_get_typec2: float
    flow_info_qcusb1: int
    flow_info_qcusb2: int
    flow_info_typec1: int
    flow_info_typec2: int
    dev_standby_time: int
    screen_off_time: int
    ac_standby_time: int
    dc_standby_time: int
    ac_always_on_flag: int
    ac_always_on_mini_soc: int
    xboost_en: int
    pcs_fan_level: int
    flow_info_12v: int
    pow_get_12v: float
    flow_info_ac2dc: int
    flow_info_dc2ac: int
    flow_info_ac_in: int
    pow_get_ac: float
    pow_get_ac_in: float
    plug_in_info_ac_in_flag: int
    plug_in_info_ac_in_feq: int
    dc_out_open: int
    cfg_ac_out_open: int
    pow_get_dcp2: float
    flow_info_dcp2_in: int
    flow_info_dcp2_out: int
    plug_in_info_dcp2_in_flag: int
    plug_in_info_dcp2_dsg_chg_type: int
    plug_in_info_dcp2_charger_flag: int
    plug_in_info_dcp2_type: int
    plug_in_info_dcp2_detail: int
    plug_in_info_dcp2_sn: str
    plug_in_info_dcp2_run_state: int
    plug_in_info_dcp2_firm_ver: int
    bms_err_code: int
    ban_bypass_en: int
    output_power_off_memory: int
    pv_chg_type: int
    flow_info_bms_dsg: int
    flow_info_bms_chg: int
    pow_get_bms: float
    en_beep: int
    plug_in_info_ac_charger_flag: int
    plug_in_info_ac_in_chg_pow_max: int
    ac_out_freq: int
    dev_sleep_state: int
    pd_err_code: int
    mppt_err_code: int
    llc_hv_lv_flag: int
    llc_inv_err_code: int
    plug_in_info_ac_out_dsg_pow_max: int
    bms_batt_soc: float
    bms_batt_soh: float
    bms_design_cap: int
    bms_dsg_rem_time: int
    bms_chg_rem_time: int
    bms_min_cell_temp: int
    bms_max_cell_temp: int
    bms_min_mos_temp: int
    bms_max_mos_temp: int
    cms_batt_soc: float
    cms_batt_soh: float
    cms_dsg_rem_time: int
    cms_chg_rem_time: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    cms_bms_run_state: int
    bms_chg_dsg_state: int
    cms_chg_dsg_state: int
    time_task_conflict_flag: int
    time_task_change_cnt: int
    ups_alram: int
    plug_in_info_pv_dc_amp_max: int
    led_mode: int
    low_power_alarm: int
    silence_chg_watt: int
    flow_info_pv: int
    pow_get_pv: float
    plug_in_info_pv_flag: int
    plug_in_info_pv_type: int
    plug_in_info_pv_charger_flag: int
    plug_in_info_pv_chg_amp_max: int
    plug_in_info_pv_chg_vol_max: int
    flow_info_ac_out: int
    pow_get_ac_out: float
    energy_strategy_operate_mode: Delta3CfgEnergyStrategyOperateMode
    self_powered_conflict_flag: int
    tou_mode_conflict_flag: int
    flow_info_dcp_in: int
    flow_info_dcp_out: int
    pow_get_dcp: float
    plug_in_info_dcp_in_flag: int
    plug_in_info_dcp_type: int
    plug_in_info_dcp_detail: int
    plug_in_info_dcp_dsg_chg_type: int
    plug_in_info_dcp_sn: str
    plug_in_info_dcp_firm_ver: int
    plug_in_info_dcp_charger_flag: int
    plug_in_info_dcp_run_state: int
    plug_in_info_dcp_err_code: int
    plug_in_info_dcp2_err_code: int
    plug_in_info_ac_in_chg_mode: int
    plug_in_info_ac_in_chg_hal_pow_max: int
    backup_reverse_soc: int
    def __init__(self, errcode: int | None = ..., pow_in_sum_w: float | None = ..., pow_out_sum_w: float | None = ..., energy_backup_en: int | None = ..., energy_backup_start_soc: int | None = ..., pow_get_qcusb1: float | None = ..., pow_get_qcusb2: float | None = ..., pow_get_typec1: float | None = ..., pow_get_typec2: float | None = ..., flow_info_qcusb1: int | None = ..., flow_info_qcusb2: int | None = ..., flow_info_typec1: int | None = ..., flow_info_typec2: int | None = ..., dev_standby_time: int | None = ..., screen_off_time: int | None = ..., ac_standby_time: int | None = ..., dc_standby_time: int | None = ..., ac_always_on_flag: int | None = ..., ac_always_on_mini_soc: int | None = ..., xboost_en: int | None = ..., pcs_fan_level: int | None = ..., flow_info_12v: int | None = ..., pow_get_12v: float | None = ..., flow_info_ac2dc: int | None = ..., flow_info_dc2ac: int | None = ..., flow_info_ac_in: int | None = ..., pow_get_ac: float | None = ..., pow_get_ac_in: float | None = ..., plug_in_info_ac_in_flag: int | None = ..., plug_in_info_ac_in_feq: int | None = ..., dc_out_open: int | None = ..., cfg_ac_out_open: int | None = ..., pow_get_dcp2: float | None = ..., flow_info_dcp2_in: int | None = ..., flow_info_dcp2_out: int | None = ..., plug_in_info_dcp2_in_flag: int | None = ..., plug_in_info_dcp2_dsg_chg_type: int | None = ..., plug_in_info_dcp2_charger_flag: int | None = ..., plug_in_info_dcp2_type: int | None = ..., plug_in_info_dcp2_detail: int | None = ..., plug_in_info_dcp2_sn: str | None = ..., plug_in_info_dcp2_run_state: int | None = ..., plug_in_info_dcp2_firm_ver: int | None = ..., bms_err_code: int | None = ..., ban_bypass_en: int | None = ..., output_power_off_memory: int | None = ..., pv_chg_type: int | None = ..., flow_info_bms_dsg: int | None = ..., flow_info_bms_chg: int | None = ..., pow_get_bms: float | None = ..., en_beep: int | None = ..., plug_in_info_ac_charger_flag: int | None = ..., plug_in_info_ac_in_chg_pow_max: int | None = ..., ac_out_freq: int | None = ..., dev_sleep_state: int | None = ..., pd_err_code: int | None = ..., mppt_err_code: int | None = ..., llc_hv_lv_flag: int | None = ..., llc_inv_err_code: int | None = ..., plug_in_info_ac_out_dsg_pow_max: int | None = ..., bms_batt_soc: float | None = ..., bms_batt_soh: float | None = ..., bms_design_cap: int | None = ..., bms_dsg_rem_time: int | None = ..., bms_chg_rem_time: int | None = ..., bms_min_cell_temp: int | None = ..., bms_max_cell_temp: int | None = ..., bms_min_mos_temp: int | None = ..., bms_max_mos_temp: int | None = ..., cms_batt_soc: float | None = ..., cms_batt_soh: float | None = ..., cms_dsg_rem_time: int | None = ..., cms_chg_rem_time: int | None = ..., cms_max_chg_soc: int | None = ..., cms_min_dsg_soc: int | None = ..., cms_bms_run_state: int | None = ..., bms_chg_dsg_state: int | None = ..., cms_chg_dsg_state: int | None = ..., time_task_conflict_flag: int | None = ..., time_task_change_cnt: int | None = ..., ups_alram: int | None = ..., plug_in_info_pv_dc_amp_max: int | None = ..., led_mode: int | None = ..., low_power_alarm: int | None = ..., silence_chg_watt: int | None = ..., flow_info_pv: int | None = ..., pow_get_pv: float | None = ..., plug_in_info_pv_flag: int | None = ..., plug_in_info_pv_type: int | None = ..., plug_in_info_pv_charger_flag: int | None = ..., plug_in_info_pv_chg_amp_max: int | None = ..., plug_in_info_pv_chg_vol_max: int | None = ..., flow_info_ac_out: int | None = ..., pow_get_ac_out: float | None = ..., energy_strategy_operate_mode: Delta3CfgEnergyStrategyOperateMode | _Mapping | None = ..., self_powered_conflict_flag: int | None = ..., tou_mode_conflict_flag: int | None = ..., flow_info_dcp_in: int | None = ..., flow_info_dcp_out: int | None = ..., pow_get_dcp: float | None = ..., plug_in_info_dcp_in_flag: int | None = ..., plug_in_info_dcp_type: int | None = ..., plug_in_info_dcp_detail: int | None = ..., plug_in_info_dcp_dsg_chg_type: int | None = ..., plug_in_info_dcp_sn: str | None = ..., plug_in_info_dcp_firm_ver: int | None = ..., plug_in_info_dcp_charger_flag: int | None = ..., plug_in_info_dcp_run_state: int | None = ..., plug_in_info_dcp_err_code: int | None = ..., plug_in_info_dcp2_err_code: int | None = ..., plug_in_info_ac_in_chg_mode: int | None = ..., plug_in_info_ac_in_chg_hal_pow_max: int | None = ..., backup_reverse_soc: int | None = ...) -> None: ...

class Delta3RuntimePropertyUpload(_message.Message):
    __slots__ = ("ac_phase_type", "bms_alm_state", "bms_alm_state_2", "bms_bal_state", "bms_batt_amp", "bms_batt_vol", "bms_err_code", "bms_firm_ver", "bms_flt_state", "bms_full_cap", "bms_high_temp_icon", "bms_limit_icon", "bms_low_temp_icon", "bms_max_cell_vol", "bms_min_cell_vol", "bms_overload_icon", "bms_pro_state", "bms_pro_state_2", "bms_remain_cap", "bms_warn_icon", "cms_batt_amp", "cms_batt_vol", "cms_chg_req_amp", "cms_chg_req_vol", "dcdc_chg_req_cur", "display_property_full_upload_period", "display_property_incremental_upload_period", "inv_main_fsmstate", "iot_firm_ver", "l1_main_fsmstate", "llc_bat_cur", "llc_bat_vol", "llc_bus_vol", "llc_inv_firm_ver", "llc_recv_cms_chg_req_vol", "mppt_firm_ver", "pcs_work_mode", "pd_bms_comm_err", "pd_firm_ver", "pd_iot_comm_err", "pd_llc_comm_err", "pd_mppt_comm_err", "plug_in_info_12v_amp", "plug_in_info_12v_vol", "plug_in_info_ac_in_amp", "plug_in_info_ac_in_vol", "plug_in_info_ac_out_amp", "plug_in_info_ac_out_freq", "plug_in_info_ac_out_type", "plug_in_info_ac_out_vol", "plug_in_info_bms_vol", "plug_in_info_dcp_amp", "plug_in_info_dcp_vol", "plug_in_info_pv_amp", "plug_in_info_pv_vol", "pv_vin_ref", "runtime_property_full_upload_period", "runtime_property_incremental_upload_period", "temp_pcs_ac", "temp_pcs_dc", "temp_pv")
    AC_PHASE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PCS_WORK_MODE_FIELD_NUMBER: _ClassVar[int]
    TEMP_PCS_DC_FIELD_NUMBER: _ClassVar[int]
    TEMP_PCS_AC_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_BMS_VOL_FIELD_NUMBER: _ClassVar[int]
    PD_MPPT_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_LLC_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_BMS_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_IOT_COMM_ERR_FIELD_NUMBER: _ClassVar[int]
    PD_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    IOT_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    MPPT_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_AMP_FIELD_NUMBER: _ClassVar[int]
    LLC_INV_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_VOL_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_BAL_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_FULL_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_REMAIN_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_ALM_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_PRO_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_FLT_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_AMP_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_OVERLOAD_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_WARN_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_HIGH_TEMP_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_LOW_TEMP_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_LIMIT_ICON_FIELD_NUMBER: _ClassVar[int]
    BMS_ALM_STATE_2_FIELD_NUMBER: _ClassVar[int]
    BMS_PRO_STATE_2_FIELD_NUMBER: _ClassVar[int]
    DISPLAY_PROPERTY_FULL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    DISPLAY_PROPERTY_INCREMENTAL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    RUNTIME_PROPERTY_FULL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    RUNTIME_PROPERTY_INCREMENTAL_UPLOAD_PERIOD_FIELD_NUMBER: _ClassVar[int]
    PV_VIN_REF_FIELD_NUMBER: _ClassVar[int]
    INV_MAIN_FSMSTATE_FIELD_NUMBER: _ClassVar[int]
    L1_MAIN_FSMSTATE_FIELD_NUMBER: _ClassVar[int]
    DCDC_CHG_REQ_CUR_FIELD_NUMBER: _ClassVar[int]
    LLC_RECV_CMS_CHG_REQ_VOL_FIELD_NUMBER: _ClassVar[int]
    TEMP_PV_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_12V_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_12V_AMP_FIELD_NUMBER: _ClassVar[int]
    LLC_BAT_VOL_FIELD_NUMBER: _ClassVar[int]
    LLC_BAT_CUR_FIELD_NUMBER: _ClassVar[int]
    LLC_BUS_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_DCP_AMP_FIELD_NUMBER: _ClassVar[int]
    ac_phase_type: int
    pcs_work_mode: int
    temp_pcs_dc: float
    temp_pcs_ac: float
    plug_in_info_ac_out_type: int
    plug_in_info_ac_out_freq: int
    plug_in_info_ac_out_vol: float
    plug_in_info_ac_in_vol: float
    plug_in_info_bms_vol: float
    pd_mppt_comm_err: int
    pd_llc_comm_err: int
    pd_bms_comm_err: int
    pd_iot_comm_err: int
    pd_firm_ver: int
    iot_firm_ver: int
    mppt_firm_ver: int
    plug_in_info_ac_in_amp: float
    plug_in_info_ac_out_amp: float
    llc_inv_firm_ver: int
    bms_firm_ver: int
    bms_batt_vol: float
    bms_batt_amp: float
    bms_bal_state: int
    bms_full_cap: int
    bms_remain_cap: int
    bms_alm_state: int
    bms_pro_state: int
    bms_flt_state: int
    bms_err_code: int
    bms_min_cell_vol: int
    bms_max_cell_vol: int
    cms_batt_vol: float
    cms_batt_amp: float
    cms_chg_req_vol: float
    cms_chg_req_amp: float
    bms_overload_icon: int
    bms_warn_icon: int
    bms_high_temp_icon: int
    bms_low_temp_icon: int
    bms_limit_icon: int
    bms_alm_state_2: int
    bms_pro_state_2: int
    display_property_full_upload_period: int
    display_property_incremental_upload_period: int
    runtime_property_full_upload_period: int
    runtime_property_incremental_upload_period: int
    pv_vin_ref: float
    inv_main_fsmstate: int
    l1_main_fsmstate: int
    dcdc_chg_req_cur: float
    llc_recv_cms_chg_req_vol: float
    temp_pv: float
    plug_in_info_pv_vol: float
    plug_in_info_pv_amp: float
    plug_in_info_12v_vol: float
    plug_in_info_12v_amp: float
    llc_bat_vol: float
    llc_bat_cur: float
    llc_bus_vol: float
    plug_in_info_dcp_vol: float
    plug_in_info_dcp_amp: float
    def __init__(self, ac_phase_type: int | None = ..., pcs_work_mode: int | None = ..., temp_pcs_dc: float | None = ..., temp_pcs_ac: float | None = ..., plug_in_info_ac_out_type: int | None = ..., plug_in_info_ac_out_freq: int | None = ..., plug_in_info_ac_out_vol: float | None = ..., plug_in_info_ac_in_vol: float | None = ..., plug_in_info_bms_vol: float | None = ..., pd_mppt_comm_err: int | None = ..., pd_llc_comm_err: int | None = ..., pd_bms_comm_err: int | None = ..., pd_iot_comm_err: int | None = ..., pd_firm_ver: int | None = ..., iot_firm_ver: int | None = ..., mppt_firm_ver: int | None = ..., plug_in_info_ac_in_amp: float | None = ..., plug_in_info_ac_out_amp: float | None = ..., llc_inv_firm_ver: int | None = ..., bms_firm_ver: int | None = ..., bms_batt_vol: float | None = ..., bms_batt_amp: float | None = ..., bms_bal_state: int | None = ..., bms_full_cap: int | None = ..., bms_remain_cap: int | None = ..., bms_alm_state: int | None = ..., bms_pro_state: int | None = ..., bms_flt_state: int | None = ..., bms_err_code: int | None = ..., bms_min_cell_vol: int | None = ..., bms_max_cell_vol: int | None = ..., cms_batt_vol: float | None = ..., cms_batt_amp: float | None = ..., cms_chg_req_vol: float | None = ..., cms_chg_req_amp: float | None = ..., bms_overload_icon: int | None = ..., bms_warn_icon: int | None = ..., bms_high_temp_icon: int | None = ..., bms_low_temp_icon: int | None = ..., bms_limit_icon: int | None = ..., bms_alm_state_2: int | None = ..., bms_pro_state_2: int | None = ..., display_property_full_upload_period: int | None = ..., display_property_incremental_upload_period: int | None = ..., runtime_property_full_upload_period: int | None = ..., runtime_property_incremental_upload_period: int | None = ..., pv_vin_ref: float | None = ..., inv_main_fsmstate: int | None = ..., l1_main_fsmstate: int | None = ..., dcdc_chg_req_cur: float | None = ..., llc_recv_cms_chg_req_vol: float | None = ..., temp_pv: float | None = ..., plug_in_info_pv_vol: float | None = ..., plug_in_info_pv_amp: float | None = ..., plug_in_info_12v_vol: float | None = ..., plug_in_info_12v_amp: float | None = ..., llc_bat_vol: float | None = ..., llc_bat_cur: float | None = ..., llc_bus_vol: float | None = ..., plug_in_info_dcp_vol: float | None = ..., plug_in_info_dcp_amp: float | None = ...) -> None: ...

class Delta3SetCommand(_message.Message):
    __slots__ = ("ac_standby_time", "backup_reverse_soc", "ban_bypass_en", "cfg_ac_out_open", "cfg_dc12v_out_open", "cfg_energy_backup", "cfg_led_mode", "cfg_power_off", "cfg_usb_open", "cfg_utc_time", "cfg_utc_timezone", "cms_max_chg_soc", "cms_min_dsg_soc", "dc_standby_time", "dev_standby_time", "en_beep", "energy_strategy_operate_mode", "lcd_light", "output_power_off_memory", "plug_in_info_ac_in_chg_mode", "plug_in_info_ac_in_chg_pow_max", "plug_in_info_pv_dc_amp_max", "pv_chg_type", "screen_off_time", "xboost_en")
    CFG_POWER_OFF_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIME_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    EN_BEEP_FIELD_NUMBER: _ClassVar[int]
    AC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    DC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    SCREEN_OFF_TIME_FIELD_NUMBER: _ClassVar[int]
    DEV_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    LCD_LIGHT_FIELD_NUMBER: _ClassVar[int]
    CFG_DC12V_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    CFG_USB_OPEN_FIELD_NUMBER: _ClassVar[int]
    XBOOST_EN_FIELD_NUMBER: _ClassVar[int]
    BAN_BYPASS_EN_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    CFG_ENERGY_BACKUP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    CFG_AC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    CFG_LED_MODE_FIELD_NUMBER: _ClassVar[int]
    PV_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    BACKUP_REVERSE_SOC_FIELD_NUMBER: _ClassVar[int]
    ENERGY_STRATEGY_OPERATE_MODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_MODE_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_POWER_OFF_MEMORY_FIELD_NUMBER: _ClassVar[int]
    cfg_power_off: int
    cfg_utc_time: int
    cfg_utc_timezone: int
    en_beep: int
    ac_standby_time: int
    dc_standby_time: int
    screen_off_time: int
    dev_standby_time: int
    lcd_light: int
    cfg_dc12v_out_open: int
    cfg_usb_open: int
    xboost_en: int
    ban_bypass_en: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    cfg_energy_backup: Delta3CfgEnergyBackup
    plug_in_info_ac_in_chg_pow_max: int
    cfg_ac_out_open: int
    plug_in_info_pv_dc_amp_max: int
    cfg_led_mode: int
    pv_chg_type: int
    backup_reverse_soc: int
    energy_strategy_operate_mode: Delta3CfgEnergyStrategyOperateMode
    plug_in_info_ac_in_chg_mode: int
    output_power_off_memory: int
    def __init__(self, cfg_power_off: int | None = ..., cfg_utc_time: int | None = ..., cfg_utc_timezone: int | None = ..., en_beep: int | None = ..., ac_standby_time: int | None = ..., dc_standby_time: int | None = ..., screen_off_time: int | None = ..., dev_standby_time: int | None = ..., lcd_light: int | None = ..., cfg_dc12v_out_open: int | None = ..., cfg_usb_open: int | None = ..., xboost_en: int | None = ..., ban_bypass_en: int | None = ..., cms_max_chg_soc: int | None = ..., cms_min_dsg_soc: int | None = ..., cfg_energy_backup: Delta3CfgEnergyBackup | _Mapping | None = ..., plug_in_info_ac_in_chg_pow_max: int | None = ..., cfg_ac_out_open: int | None = ..., plug_in_info_pv_dc_amp_max: int | None = ..., cfg_led_mode: int | None = ..., pv_chg_type: int | None = ..., backup_reverse_soc: int | None = ..., energy_strategy_operate_mode: Delta3CfgEnergyStrategyOperateMode | _Mapping | None = ..., plug_in_info_ac_in_chg_mode: int | None = ..., output_power_off_memory: int | None = ...) -> None: ...

class Delta3SetReply(_message.Message):
    __slots__ = ("ac_standby_time", "action_id", "backup_reverse_soc", "ban_bypass_en", "cfg_ac_out_open", "cfg_dc12v_out_open", "cfg_energy_backup", "cfg_led_mode", "cfg_usb_open", "cfg_utc_time", "cfg_utc_timezone", "cms_max_chg_soc", "cms_min_dsg_soc", "config_ok", "dc_out_open", "dc_standby_time", "dev_standby_time", "en_beep", "energy_strategy_operate_mode", "lcd_light", "output_power_off_memory", "plug_in_info_ac_in_chg_mode", "plug_in_info_ac_in_chg_pow_max", "plug_in_info_pv_dc_amp_max", "pv_chg_type", "screen_off_time", "xboost_en")
    ACTION_ID_FIELD_NUMBER: _ClassVar[int]
    CONFIG_OK_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIME_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    EN_BEEP_FIELD_NUMBER: _ClassVar[int]
    AC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    DC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    SCREEN_OFF_TIME_FIELD_NUMBER: _ClassVar[int]
    DEV_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    LCD_LIGHT_FIELD_NUMBER: _ClassVar[int]
    CFG_DC12V_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    CFG_USB_OPEN_FIELD_NUMBER: _ClassVar[int]
    XBOOST_EN_FIELD_NUMBER: _ClassVar[int]
    BAN_BYPASS_EN_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    CFG_ENERGY_BACKUP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    DC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    CFG_AC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    CFG_LED_MODE_FIELD_NUMBER: _ClassVar[int]
    PV_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    BACKUP_REVERSE_SOC_FIELD_NUMBER: _ClassVar[int]
    ENERGY_STRATEGY_OPERATE_MODE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_MODE_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_POWER_OFF_MEMORY_FIELD_NUMBER: _ClassVar[int]
    action_id: int
    config_ok: bool
    cfg_utc_time: int
    cfg_utc_timezone: int
    en_beep: int
    ac_standby_time: int
    dc_standby_time: int
    screen_off_time: int
    dev_standby_time: int
    lcd_light: int
    cfg_dc12v_out_open: int
    cfg_usb_open: int
    xboost_en: int
    ban_bypass_en: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    cfg_energy_backup: Delta3CfgEnergyBackup
    plug_in_info_ac_in_chg_pow_max: int
    dc_out_open: int
    cfg_ac_out_open: int
    plug_in_info_pv_dc_amp_max: int
    cfg_led_mode: int
    pv_chg_type: int
    backup_reverse_soc: int
    energy_strategy_operate_mode: Delta3CfgEnergyStrategyOperateMode
    plug_in_info_ac_in_chg_mode: int
    output_power_off_memory: int
    def __init__(self, action_id: int | None = ..., config_ok: bool | None = ..., cfg_utc_time: int | None = ..., cfg_utc_timezone: int | None = ..., en_beep: int | None = ..., ac_standby_time: int | None = ..., dc_standby_time: int | None = ..., screen_off_time: int | None = ..., dev_standby_time: int | None = ..., lcd_light: int | None = ..., cfg_dc12v_out_open: int | None = ..., cfg_usb_open: int | None = ..., xboost_en: int | None = ..., ban_bypass_en: int | None = ..., cms_max_chg_soc: int | None = ..., cms_min_dsg_soc: int | None = ..., cfg_energy_backup: Delta3CfgEnergyBackup | _Mapping | None = ..., plug_in_info_ac_in_chg_pow_max: int | None = ..., dc_out_open: int | None = ..., cfg_ac_out_open: int | None = ..., plug_in_info_pv_dc_amp_max: int | None = ..., cfg_led_mode: int | None = ..., pv_chg_type: int | None = ..., backup_reverse_soc: int | None = ..., energy_strategy_operate_mode: Delta3CfgEnergyStrategyOperateMode | _Mapping | None = ..., plug_in_info_ac_in_chg_mode: int | None = ..., output_power_off_memory: int | None = ...) -> None: ...

class Delta3CfgEnergyBackup(_message.Message):
    __slots__ = ("energy_backup_en", "energy_backup_start_soc")
    ENERGY_BACKUP_EN_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_START_SOC_FIELD_NUMBER: _ClassVar[int]
    energy_backup_en: int
    energy_backup_start_soc: int
    def __init__(self, energy_backup_en: int | None = ..., energy_backup_start_soc: int | None = ...) -> None: ...

class Delta3CfgEnergyStrategyOperateMode(_message.Message):
    __slots__ = ("operate_scheduled_open", "operate_self_powered_open", "operate_tou_mode_open")
    OPERATE_SELF_POWERED_OPEN_FIELD_NUMBER: _ClassVar[int]
    OPERATE_SCHEDULED_OPEN_FIELD_NUMBER: _ClassVar[int]
    OPERATE_TOU_MODE_OPEN_FIELD_NUMBER: _ClassVar[int]
    operate_self_powered_open: int
    operate_scheduled_open: int
    operate_tou_mode_open: int
    def __init__(self, operate_self_powered_open: int | None = ..., operate_scheduled_open: int | None = ..., operate_tou_mode_open: int | None = ...) -> None: ...

class Delta3CMSHeartBeatReport(_message.Message):
    __slots__ = ("msg32_2_1", "msg32_2_2")
    MSG32_2_1_FIELD_NUMBER: _ClassVar[int]
    MSG32_2_2_FIELD_NUMBER: _ClassVar[int]
    msg32_2_1: Delta3CMSStatus1
    msg32_2_2: Delta3CMSStatus2
    def __init__(self, msg32_2_1: Delta3CMSStatus1 | _Mapping | None = ..., msg32_2_2: Delta3CMSStatus2 | _Mapping | None = ...) -> None: ...

class Delta3CMSStatus1(_message.Message):
    __slots__ = ("ac_out_freq", "bms_is_conn_state", "cms_batt_soc", "cms_batt_vol_mv", "cms_chg_dsg_state", "cms_chg_rem_time", "cms_chg_req_amp", "cms_dsg_rem_time", "cms_max_chg_soc", "cms_min_dsg_soc", "cms_oil_off_soc", "cms_status_misc1", "cms_status_misc2", "cms_status_misc3", "cms_status_misc4", "cms_status_misc5", "cms_status_misc6", "cms_status_misc7", "cms_status_misc8", "cms_status_misc9", "cms_status_misc10", "cms_status_misc11", "cms_status_misc12")
    CMS_STATUS_MISC1_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC2_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC3_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_VOL_MV_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_AMP_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC4_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC5_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC6_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    BMS_IS_CONN_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC7_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC8_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC9_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC10_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC11_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC12_FIELD_NUMBER: _ClassVar[int]
    CMS_OIL_OFF_SOC_FIELD_NUMBER: _ClassVar[int]
    cms_status_misc1: int
    cms_status_misc2: int
    cms_status_misc3: int
    cms_batt_vol_mv: int
    cms_chg_req_amp: int
    cms_status_misc4: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    ac_out_freq: int
    cms_status_misc5: int
    cms_status_misc6: int
    cms_chg_rem_time: int
    cms_dsg_rem_time: int
    cms_chg_dsg_state: int
    cms_batt_soc: float
    bms_is_conn_state: _containers.RepeatedScalarFieldContainer[int]
    cms_status_misc7: int
    cms_status_misc8: int
    cms_status_misc9: int
    cms_status_misc10: int
    cms_status_misc11: int
    cms_status_misc12: int
    cms_oil_off_soc: int
    def __init__(self, cms_status_misc1: int | None = ..., cms_status_misc2: int | None = ..., cms_status_misc3: int | None = ..., cms_batt_vol_mv: int | None = ..., cms_chg_req_amp: int | None = ..., cms_status_misc4: int | None = ..., cms_max_chg_soc: int | None = ..., cms_min_dsg_soc: int | None = ..., ac_out_freq: int | None = ..., cms_status_misc5: int | None = ..., cms_status_misc6: int | None = ..., cms_chg_rem_time: int | None = ..., cms_dsg_rem_time: int | None = ..., cms_chg_dsg_state: int | None = ..., cms_batt_soc: float | None = ..., bms_is_conn_state: _Iterable[int] | None = ..., cms_status_misc7: int | None = ..., cms_status_misc8: int | None = ..., cms_status_misc9: int | None = ..., cms_status_misc10: int | None = ..., cms_status_misc11: int | None = ..., cms_status_misc12: int | None = ..., cms_oil_off_soc: int | None = ...) -> None: ...

class Delta3CMSStatus2(_message.Message):
    __slots__ = ("cms_status_misc13", "cms_status_misc14", "cms_status_misc15", "cms_status_misc16", "cms_status_misc17")
    CMS_STATUS_MISC13_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC14_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC15_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC16_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC17_FIELD_NUMBER: _ClassVar[int]
    cms_status_misc13: int
    cms_status_misc14: int
    cms_status_misc15: int
    cms_status_misc16: int
    cms_status_misc17: int
    def __init__(self, cms_status_misc13: int | None = ..., cms_status_misc14: int | None = ..., cms_status_misc15: int | None = ..., cms_status_misc16: int | None = ..., cms_status_misc17: int | None = ...) -> None: ...

class Delta3BMSHeartBeatReport(_message.Message):
    __slots__ = ("accu_chg_cap", "accu_chg_energy", "accu_dsg_cap", "accu_dsg_energy", "act_soc", "afe_sys_status", "all_bms_fault", "all_err_code", "amp", "balance_cmd", "balance_state", "bms_alarm_state1", "bms_alarm_state2", "bms_fault", "bms_fault_state", "bms_heartbeat_ver", "bms_protect_state1", "bms_protect_state2", "bms_sn", "bq_sys_stat_reg", "calendar_soh", "cell_id", "cell_ntc_num", "cell_series_num", "cell_temp", "cell_vol", "chg_dsg_state", "cur_sensor_ntc_num", "cur_sensor_temp", "cycle_soh", "cycles", "design_cap", "diff_soc", "ecloud_ocv", "env_ntc_num", "env_temp", "err_code", "f32_show_soc", "full_cap", "heatfilm_ntc_num", "heatfilm_temp", "hw_ver", "input_watts", "max_cell_temp", "max_cell_vol", "max_cur_sensor_temp", "max_env_temp", "max_heatfilm_temp", "max_mos_temp", "max_vol_diff", "mcu_pin_in_status", "mcu_pin_out_status", "min_cell_temp", "min_cell_vol", "min_cur_sensor_temp", "min_env_temp", "min_heatfilm_temp", "min_mos_temp", "mos_ntc_num", "mos_state", "mos_temp", "num", "open_bms_flag", "output_watts", "pack_sn", "product_detail", "product_type", "real_soh", "remain_balance_time", "remain_cap", "remain_time", "soc", "soh", "sys_loader_ver", "sys_state", "sys_ver", "tag_chg_amp", "target_soc", "temp", "type", "vol", "water_in_flag")
    NUM_FIELD_NUMBER: _ClassVar[int]
    TYPE_FIELD_NUMBER: _ClassVar[int]
    CELL_ID_FIELD_NUMBER: _ClassVar[int]
    ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    SYS_VER_FIELD_NUMBER: _ClassVar[int]
    SOC_FIELD_NUMBER: _ClassVar[int]
    VOL_FIELD_NUMBER: _ClassVar[int]
    AMP_FIELD_NUMBER: _ClassVar[int]
    TEMP_FIELD_NUMBER: _ClassVar[int]
    OPEN_BMS_FLAG_FIELD_NUMBER: _ClassVar[int]
    DESIGN_CAP_FIELD_NUMBER: _ClassVar[int]
    REMAIN_CAP_FIELD_NUMBER: _ClassVar[int]
    FULL_CAP_FIELD_NUMBER: _ClassVar[int]
    CYCLES_FIELD_NUMBER: _ClassVar[int]
    SOH_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_FAULT_FIELD_NUMBER: _ClassVar[int]
    BQ_SYS_STAT_REG_FIELD_NUMBER: _ClassVar[int]
    TAG_CHG_AMP_FIELD_NUMBER: _ClassVar[int]
    F32_SHOW_SOC_FIELD_NUMBER: _ClassVar[int]
    INPUT_WATTS_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_WATTS_FIELD_NUMBER: _ClassVar[int]
    REMAIN_TIME_FIELD_NUMBER: _ClassVar[int]
    MOS_STATE_FIELD_NUMBER: _ClassVar[int]
    BALANCE_STATE_FIELD_NUMBER: _ClassVar[int]
    MAX_VOL_DIFF_FIELD_NUMBER: _ClassVar[int]
    CELL_SERIES_NUM_FIELD_NUMBER: _ClassVar[int]
    CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    CELL_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    HW_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_HEARTBEAT_VER_FIELD_NUMBER: _ClassVar[int]
    ECLOUD_OCV_FIELD_NUMBER: _ClassVar[int]
    BMS_SN_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_TYPE_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_DETAIL_FIELD_NUMBER: _ClassVar[int]
    ACT_SOC_FIELD_NUMBER: _ClassVar[int]
    DIFF_SOC_FIELD_NUMBER: _ClassVar[int]
    TARGET_SOC_FIELD_NUMBER: _ClassVar[int]
    SYS_LOADER_VER_FIELD_NUMBER: _ClassVar[int]
    SYS_STATE_FIELD_NUMBER: _ClassVar[int]
    CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    ALL_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    ALL_BMS_FAULT_FIELD_NUMBER: _ClassVar[int]
    ACCU_CHG_CAP_FIELD_NUMBER: _ClassVar[int]
    ACCU_DSG_CAP_FIELD_NUMBER: _ClassVar[int]
    REAL_SOH_FIELD_NUMBER: _ClassVar[int]
    CALENDAR_SOH_FIELD_NUMBER: _ClassVar[int]
    CYCLE_SOH_FIELD_NUMBER: _ClassVar[int]
    MOS_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    ENV_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    HEATFILM_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    CUR_SENSOR_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    BALANCE_CMD_FIELD_NUMBER: _ClassVar[int]
    REMAIN_BALANCE_TIME_FIELD_NUMBER: _ClassVar[int]
    AFE_SYS_STATUS_FIELD_NUMBER: _ClassVar[int]
    MCU_PIN_IN_STATUS_FIELD_NUMBER: _ClassVar[int]
    MCU_PIN_OUT_STATUS_FIELD_NUMBER: _ClassVar[int]
    BMS_ALARM_STATE1_FIELD_NUMBER: _ClassVar[int]
    BMS_ALARM_STATE2_FIELD_NUMBER: _ClassVar[int]
    BMS_PROTECT_STATE1_FIELD_NUMBER: _ClassVar[int]
    BMS_PROTECT_STATE2_FIELD_NUMBER: _ClassVar[int]
    BMS_FAULT_STATE_FIELD_NUMBER: _ClassVar[int]
    ACCU_CHG_ENERGY_FIELD_NUMBER: _ClassVar[int]
    ACCU_DSG_ENERGY_FIELD_NUMBER: _ClassVar[int]
    PACK_SN_FIELD_NUMBER: _ClassVar[int]
    WATER_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    num: int
    type: int
    cell_id: int
    err_code: int
    sys_ver: int
    soc: int
    vol: int
    amp: int
    temp: int
    open_bms_flag: int
    design_cap: int
    remain_cap: int
    full_cap: int
    cycles: int
    soh: int
    max_cell_vol: int
    min_cell_vol: int
    max_cell_temp: int
    min_cell_temp: int
    max_mos_temp: int
    min_mos_temp: int
    bms_fault: int
    bq_sys_stat_reg: int
    tag_chg_amp: int
    f32_show_soc: float
    input_watts: int
    output_watts: int
    remain_time: int
    mos_state: int
    balance_state: int
    max_vol_diff: int
    cell_series_num: int
    cell_vol: _containers.RepeatedScalarFieldContainer[int]
    cell_ntc_num: int
    cell_temp: _containers.RepeatedScalarFieldContainer[int]
    hw_ver: str
    bms_heartbeat_ver: int
    ecloud_ocv: int
    bms_sn: str
    product_type: int
    product_detail: int
    act_soc: float
    diff_soc: float
    target_soc: float
    sys_loader_ver: int
    sys_state: int
    chg_dsg_state: int
    all_err_code: int
    all_bms_fault: int
    accu_chg_cap: int
    accu_dsg_cap: int
    real_soh: float
    calendar_soh: float
    cycle_soh: float
    mos_ntc_num: int
    mos_temp: _containers.RepeatedScalarFieldContainer[int]
    env_ntc_num: int
    env_temp: _containers.RepeatedScalarFieldContainer[int]
    heatfilm_ntc_num: int
    heatfilm_temp: _containers.RepeatedScalarFieldContainer[int]
    cur_sensor_ntc_num: int
    cur_sensor_temp: _containers.RepeatedScalarFieldContainer[int]
    max_env_temp: int
    min_env_temp: int
    max_heatfilm_temp: int
    min_heatfilm_temp: int
    max_cur_sensor_temp: int
    min_cur_sensor_temp: int
    balance_cmd: int
    remain_balance_time: _containers.RepeatedScalarFieldContainer[int]
    afe_sys_status: int
    mcu_pin_in_status: int
    mcu_pin_out_status: int
    bms_alarm_state1: int
    bms_alarm_state2: int
    bms_protect_state1: int
    bms_protect_state2: int
    bms_fault_state: int
    accu_chg_energy: int
    accu_dsg_energy: int
    pack_sn: str
    water_in_flag: int
    def __init__(self, num: int | None = ..., type: int | None = ..., cell_id: int | None = ..., err_code: int | None = ..., sys_ver: int | None = ..., soc: int | None = ..., vol: int | None = ..., amp: int | None = ..., temp: int | None = ..., open_bms_flag: int | None = ..., design_cap: int | None = ..., remain_cap: int | None = ..., full_cap: int | None = ..., cycles: int | None = ..., soh: int | None = ..., max_cell_vol: int | None = ..., min_cell_vol: int | None = ..., max_cell_temp: int | None = ..., min_cell_temp: int | None = ..., max_mos_temp: int | None = ..., min_mos_temp: int | None = ..., bms_fault: int | None = ..., bq_sys_stat_reg: int | None = ..., tag_chg_amp: int | None = ..., f32_show_soc: float | None = ..., input_watts: int | None = ..., output_watts: int | None = ..., remain_time: int | None = ..., mos_state: int | None = ..., balance_state: int | None = ..., max_vol_diff: int | None = ..., cell_series_num: int | None = ..., cell_vol: _Iterable[int] | None = ..., cell_ntc_num: int | None = ..., cell_temp: _Iterable[int] | None = ..., hw_ver: str | None = ..., bms_heartbeat_ver: int | None = ..., ecloud_ocv: int | None = ..., bms_sn: str | None = ..., product_type: int | None = ..., product_detail: int | None = ..., act_soc: float | None = ..., diff_soc: float | None = ..., target_soc: float | None = ..., sys_loader_ver: int | None = ..., sys_state: int | None = ..., chg_dsg_state: int | None = ..., all_err_code: int | None = ..., all_bms_fault: int | None = ..., accu_chg_cap: int | None = ..., accu_dsg_cap: int | None = ..., real_soh: float | None = ..., calendar_soh: float | None = ..., cycle_soh: float | None = ..., mos_ntc_num: int | None = ..., mos_temp: _Iterable[int] | None = ..., env_ntc_num: int | None = ..., env_temp: _Iterable[int] | None = ..., heatfilm_ntc_num: int | None = ..., heatfilm_temp: _Iterable[int] | None = ..., cur_sensor_ntc_num: int | None = ..., cur_sensor_temp: _Iterable[int] | None = ..., max_env_temp: int | None = ..., min_env_temp: int | None = ..., max_heatfilm_temp: int | None = ..., min_heatfilm_temp: int | None = ..., max_cur_sensor_temp: int | None = ..., min_cur_sensor_temp: int | None = ..., balance_cmd: int | None = ..., remain_balance_time: _Iterable[int] | None = ..., afe_sys_status: int | None = ..., mcu_pin_in_status: int | None = ..., mcu_pin_out_status: int | None = ..., bms_alarm_state1: int | None = ..., bms_alarm_state2: int | None = ..., bms_protect_state1: int | None = ..., bms_protect_state2: int | None = ..., bms_fault_state: int | None = ..., accu_chg_energy: int | None = ..., accu_dsg_energy: int | None = ..., pack_sn: str | None = ..., water_in_flag: int | None = ...) -> None: ...

class Delta3HeaderMessage(_message.Message):
    __slots__ = ("header",)
    HEADER_FIELD_NUMBER: _ClassVar[int]
    header: _containers.RepeatedCompositeFieldContainer[Delta3Header]
    def __init__(self, header: _Iterable[Delta3Header | _Mapping] | None = ...) -> None: ...
