# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ef_delta_pro_ultra_x.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'ef_delta_pro_ultra_x.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65\x66_delta_pro_ultra_x.proto\"\x94\x01\n\x08\x44PUXPack\x12\x10\n\x03\x62\x61y\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x10\n\x03soc\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x10\n\x03\x61mp\x18\x05 \x01(\x02H\x02\x88\x01\x01\x12\x13\n\x06\x64\x65sign\x18\x06 \x01(\x02H\x03\x88\x01\x01\x12\x11\n\x04temp\x18\x08 \x01(\x05H\x04\x88\x01\x01\x42\x06\n\x04_bayB\x06\n\x04_socB\x06\n\x04_ampB\t\n\x07_designB\x07\n\x05_temp\"&\n\nDPUXBpInfo\x12\x18\n\x05packs\x18\x01 \x03(\x0b\x32\t.DPUXPack\"J\n\x18\x44PUXDisplayPropertyExtra\x12\"\n\x07\x62p_info\x18\x92\x06 \x01(\x0b\x32\x0b.DPUXBpInfoH\x00\x88\x01\x01\x42\n\n\x08_bp_infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ef_delta_pro_ultra_x_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DPUXPACK']._serialized_start=31
  _globals['_DPUXPACK']._serialized_end=179
  _globals['_DPUXBPINFO']._serialized_start=181
  _globals['_DPUXBPINFO']._serialized_end=219
  _globals['_DPUXDISPLAYPROPERTYEXTRA']._serialized_start=221
  _globals['_DPUXDISPLAYPROPERTYEXTRA']._serialized_end=295
# @@protoc_insertion_point(module_scope)
