import ecopacket_pb2 as _ecopacket_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class River3DisplayPropertyUpload(_message.Message):
    __slots__ = ("errcode", "pow_in_sum_w", "pow_out_sum_w", "lcd_light", "energy_backup_state", "energy_backup_en", "energy_backup_start_soc", "pow_get_qcusb1", "pow_get_qcusb2", "pow_get_typec1", "flow_info_qcusb1", "flow_info_qcusb2", "flow_info_typec1", "dev_standby_time", "screen_off_time", "ac_standby_time", "dc_standby_time", "xboost_en", "pcs_fan_level", "flow_info_pv", "flow_info_12v", "pow_get_pv", "pow_get_12v", "plug_in_info_pv_flag", "plug_in_info_pv_type", "flow_info_ac2dc", "flow_info_dc2ac", "flow_info_ac_in", "flow_info_ac_out", "pow_get_llc", "pow_get_ac", "pow_get_ac_in", "plug_in_info_ac_in_flag", "plug_in_info_ac_in_feq", "dc_out_open", "cfg_ac_out_open", "plug_in_info_pv_dc_amp_max", "pv_chg_type", "utc_timezone", "utc_timezone_id", "utc_set_mode", "bms_err_code", "output_power_off_memory", "flow_info_bms_dsg", "flow_info_bms_chg", "pow_get_bms", "en_beep", "plug_in_info_ac_charger_flag", "plug_in_info_ac_in_chg_pow_max", "ac_out_freq", "dev_sleep_state", "pd_err_code", "llc_err_code", "mppt_err_code", "bms_batt_soc", "bms_batt_soh", "bms_design_cap", "bms_dsg_rem_time", "bms_chg_rem_time", "bms_min_cell_temp", "bms_max_cell_temp", "bms_min_mos_temp", "bms_max_mos_temp", "cms_batt_soc", "cms_batt_soh", "cms_dsg_rem_time", "cms_chg_rem_time", "cms_max_chg_soc", "cms_min_dsg_soc", "cms_bms_run_state", "bms_chg_dsg_state", "cms_chg_dsg_state", "ble_standby_time")
    ERRCODE_FIELD_NUMBER: _ClassVar[int]
    POW_IN_SUM_W_FIELD_NUMBER: _ClassVar[int]
    POW_OUT_SUM_W_FIELD_NUMBER: _ClassVar[int]
    LCD_LIGHT_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_STATE_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_EN_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_START_SOC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_QCUSB1_FIELD_NUMBER: _ClassVar[int]
    POW_GET_QCUSB2_FIELD_NUMBER: _ClassVar[int]
    POW_GET_TYPEC1_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_QCUSB1_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_QCUSB2_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_TYPEC1_FIELD_NUMBER: _ClassVar[int]
    DEV_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    SCREEN_OFF_TIME_FIELD_NUMBER: _ClassVar[int]
    AC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    DC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    XBOOST_EN_FIELD_NUMBER: _ClassVar[int]
    PCS_FAN_LEVEL_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_PV_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_12V_FIELD_NUMBER: _ClassVar[int]
    POW_GET_PV_FIELD_NUMBER: _ClassVar[int]
    POW_GET_12V_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_TYPE_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC2DC_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_DC2AC_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC_IN_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_AC_OUT_FIELD_NUMBER: _ClassVar[int]
    POW_GET_LLC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_FIELD_NUMBER: _ClassVar[int]
    POW_GET_AC_IN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_FEQ_FIELD_NUMBER: _ClassVar[int]
    DC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    CFG_AC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    PV_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    UTC_TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    UTC_TIMEZONE_ID_FIELD_NUMBER: _ClassVar[int]
    UTC_SET_MODE_FIELD_NUMBER: _ClassVar[int]
    BMS_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_POWER_OFF_MEMORY_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_BMS_DSG_FIELD_NUMBER: _ClassVar[int]
    FLOW_INFO_BMS_CHG_FIELD_NUMBER: _ClassVar[int]
    POW_GET_BMS_FIELD_NUMBER: _ClassVar[int]
    EN_BEEP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_CHARGER_FLAG_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    DEV_SLEEP_STATE_FIELD_NUMBER: _ClassVar[int]
    PD_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    LLC_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    MPPT_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_SOH_FIELD_NUMBER: _ClassVar[int]
    BMS_DESIGN_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOH_FIELD_NUMBER: _ClassVar[int]
    CMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_BMS_RUN_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    BLE_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    errcode: int
    pow_in_sum_w: float
    pow_out_sum_w: float
    lcd_light: int
    energy_backup_state: int
    energy_backup_en: int
    energy_backup_start_soc: int
    pow_get_qcusb1: float
    pow_get_qcusb2: float
    pow_get_typec1: float
    flow_info_qcusb1: int
    flow_info_qcusb2: int
    flow_info_typec1: int
    dev_standby_time: int
    screen_off_time: int
    ac_standby_time: int
    dc_standby_time: int
    xboost_en: int
    pcs_fan_level: int
    flow_info_pv: int
    flow_info_12v: int
    pow_get_pv: float
    pow_get_12v: float
    plug_in_info_pv_flag: int
    plug_in_info_pv_type: int
    flow_info_ac2dc: int
    flow_info_dc2ac: int
    flow_info_ac_in: int
    flow_info_ac_out: int
    pow_get_llc: float
    pow_get_ac: float
    pow_get_ac_in: float
    plug_in_info_ac_in_flag: int
    plug_in_info_ac_in_feq: int
    dc_out_open: int
    cfg_ac_out_open: int
    plug_in_info_pv_dc_amp_max: int
    pv_chg_type: int
    utc_timezone: int
    utc_timezone_id: str
    utc_set_mode: int
    bms_err_code: int
    output_power_off_memory: int
    flow_info_bms_dsg: int
    flow_info_bms_chg: int
    pow_get_bms: float
    en_beep: int
    plug_in_info_ac_charger_flag: int
    plug_in_info_ac_in_chg_pow_max: int
    ac_out_freq: int
    dev_sleep_state: int
    pd_err_code: int
    llc_err_code: int
    mppt_err_code: int
    bms_batt_soc: float
    bms_batt_soh: float
    bms_design_cap: int
    bms_dsg_rem_time: int
    bms_chg_rem_time: int
    bms_min_cell_temp: int
    bms_max_cell_temp: int
    bms_min_mos_temp: int
    bms_max_mos_temp: int
    cms_batt_soc: float
    cms_batt_soh: float
    cms_dsg_rem_time: int
    cms_chg_rem_time: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    cms_bms_run_state: int
    bms_chg_dsg_state: int
    cms_chg_dsg_state: int
    ble_standby_time: int
    def __init__(self, errcode: _Optional[int] = ..., pow_in_sum_w: _Optional[float] = ..., pow_out_sum_w: _Optional[float] = ..., lcd_light: _Optional[int] = ..., energy_backup_state: _Optional[int] = ..., energy_backup_en: _Optional[int] = ..., energy_backup_start_soc: _Optional[int] = ..., pow_get_qcusb1: _Optional[float] = ..., pow_get_qcusb2: _Optional[float] = ..., pow_get_typec1: _Optional[float] = ..., flow_info_qcusb1: _Optional[int] = ..., flow_info_qcusb2: _Optional[int] = ..., flow_info_typec1: _Optional[int] = ..., dev_standby_time: _Optional[int] = ..., screen_off_time: _Optional[int] = ..., ac_standby_time: _Optional[int] = ..., dc_standby_time: _Optional[int] = ..., xboost_en: _Optional[int] = ..., pcs_fan_level: _Optional[int] = ..., flow_info_pv: _Optional[int] = ..., flow_info_12v: _Optional[int] = ..., pow_get_pv: _Optional[float] = ..., pow_get_12v: _Optional[float] = ..., plug_in_info_pv_flag: _Optional[int] = ..., plug_in_info_pv_type: _Optional[int] = ..., flow_info_ac2dc: _Optional[int] = ..., flow_info_dc2ac: _Optional[int] = ..., flow_info_ac_in: _Optional[int] = ..., flow_info_ac_out: _Optional[int] = ..., pow_get_llc: _Optional[float] = ..., pow_get_ac: _Optional[float] = ..., pow_get_ac_in: _Optional[float] = ..., plug_in_info_ac_in_flag: _Optional[int] = ..., plug_in_info_ac_in_feq: _Optional[int] = ..., dc_out_open: _Optional[int] = ..., cfg_ac_out_open: _Optional[int] = ..., plug_in_info_pv_dc_amp_max: _Optional[int] = ..., pv_chg_type: _Optional[int] = ..., utc_timezone: _Optional[int] = ..., utc_timezone_id: _Optional[str] = ..., utc_set_mode: _Optional[int] = ..., bms_err_code: _Optional[int] = ..., output_power_off_memory: _Optional[int] = ..., flow_info_bms_dsg: _Optional[int] = ..., flow_info_bms_chg: _Optional[int] = ..., pow_get_bms: _Optional[float] = ..., en_beep: _Optional[int] = ..., plug_in_info_ac_charger_flag: _Optional[int] = ..., plug_in_info_ac_in_chg_pow_max: _Optional[int] = ..., ac_out_freq: _Optional[int] = ..., dev_sleep_state: _Optional[int] = ..., pd_err_code: _Optional[int] = ..., llc_err_code: _Optional[int] = ..., mppt_err_code: _Optional[int] = ..., bms_batt_soc: _Optional[float] = ..., bms_batt_soh: _Optional[float] = ..., bms_design_cap: _Optional[int] = ..., bms_dsg_rem_time: _Optional[int] = ..., bms_chg_rem_time: _Optional[int] = ..., bms_min_cell_temp: _Optional[int] = ..., bms_max_cell_temp: _Optional[int] = ..., bms_min_mos_temp: _Optional[int] = ..., bms_max_mos_temp: _Optional[int] = ..., cms_batt_soc: _Optional[float] = ..., cms_batt_soh: _Optional[float] = ..., cms_dsg_rem_time: _Optional[int] = ..., cms_chg_rem_time: _Optional[int] = ..., cms_max_chg_soc: _Optional[int] = ..., cms_min_dsg_soc: _Optional[int] = ..., cms_bms_run_state: _Optional[int] = ..., bms_chg_dsg_state: _Optional[int] = ..., cms_chg_dsg_state: _Optional[int] = ..., ble_standby_time: _Optional[int] = ...) -> None: ...

class River3RuntimePropertyUpload(_message.Message):
    __slots__ = ("pcs_work_mode", "temp_pcs_dc", "temp_pcs_ac", "temp_pv", "plug_in_info_pv_vol", "plug_in_info_pv_amp", "plug_in_info_ac_out_type", "plug_in_info_ac_out_freq", "plug_in_info_ac_in_vol", "plug_in_info_ac_out_vol", "pd_firm_ver", "iot_firm_ver", "mppt_firm_ver", "llc_firm_ver", "plug_in_info_ac_in_amp", "bms_firm_ver", "bms_batt_vol", "bms_batt_amp", "bms_bal_state", "bms_full_cap", "bms_remain_cap", "bms_alm_state", "bms_pro_state", "bms_flt_state", "bms_err_code", "bms_min_cell_vol", "bms_max_cell_vol", "cms_batt_vol", "cms_batt_amp", "cms_chg_req_vol", "cms_chg_req_amp", "bms_alm_state_2", "bms_pro_state_2")
    PCS_WORK_MODE_FIELD_NUMBER: _ClassVar[int]
    TEMP_PCS_DC_FIELD_NUMBER: _ClassVar[int]
    TEMP_PCS_AC_FIELD_NUMBER: _ClassVar[int]
    TEMP_PV_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_AMP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_TYPE_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_VOL_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_OUT_VOL_FIELD_NUMBER: _ClassVar[int]
    PD_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    IOT_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    MPPT_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    LLC_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_FIRM_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_VOL_FIELD_NUMBER: _ClassVar[int]
    BMS_BATT_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_BAL_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_FULL_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_REMAIN_CAP_FIELD_NUMBER: _ClassVar[int]
    BMS_ALM_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_PRO_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_FLT_STATE_FIELD_NUMBER: _ClassVar[int]
    BMS_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    BMS_MIN_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    BMS_MAX_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_AMP_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_VOL_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_AMP_FIELD_NUMBER: _ClassVar[int]
    BMS_ALM_STATE_2_FIELD_NUMBER: _ClassVar[int]
    BMS_PRO_STATE_2_FIELD_NUMBER: _ClassVar[int]
    pcs_work_mode: int
    temp_pcs_dc: float
    temp_pcs_ac: float
    temp_pv: float
    plug_in_info_pv_vol: float
    plug_in_info_pv_amp: float
    plug_in_info_ac_out_type: int
    plug_in_info_ac_out_freq: int
    plug_in_info_ac_in_vol: float
    plug_in_info_ac_out_vol: float
    pd_firm_ver: int
    iot_firm_ver: int
    mppt_firm_ver: int
    llc_firm_ver: int
    plug_in_info_ac_in_amp: float
    bms_firm_ver: int
    bms_batt_vol: float
    bms_batt_amp: float
    bms_bal_state: int
    bms_full_cap: int
    bms_remain_cap: int
    bms_alm_state: int
    bms_pro_state: int
    bms_flt_state: int
    bms_err_code: int
    bms_min_cell_vol: int
    bms_max_cell_vol: int
    cms_batt_vol: float
    cms_batt_amp: float
    cms_chg_req_vol: float
    cms_chg_req_amp: float
    bms_alm_state_2: int
    bms_pro_state_2: int
    def __init__(self, pcs_work_mode: _Optional[int] = ..., temp_pcs_dc: _Optional[float] = ..., temp_pcs_ac: _Optional[float] = ..., temp_pv: _Optional[float] = ..., plug_in_info_pv_vol: _Optional[float] = ..., plug_in_info_pv_amp: _Optional[float] = ..., plug_in_info_ac_out_type: _Optional[int] = ..., plug_in_info_ac_out_freq: _Optional[int] = ..., plug_in_info_ac_in_vol: _Optional[float] = ..., plug_in_info_ac_out_vol: _Optional[float] = ..., pd_firm_ver: _Optional[int] = ..., iot_firm_ver: _Optional[int] = ..., mppt_firm_ver: _Optional[int] = ..., llc_firm_ver: _Optional[int] = ..., plug_in_info_ac_in_amp: _Optional[float] = ..., bms_firm_ver: _Optional[int] = ..., bms_batt_vol: _Optional[float] = ..., bms_batt_amp: _Optional[float] = ..., bms_bal_state: _Optional[int] = ..., bms_full_cap: _Optional[int] = ..., bms_remain_cap: _Optional[int] = ..., bms_alm_state: _Optional[int] = ..., bms_pro_state: _Optional[int] = ..., bms_flt_state: _Optional[int] = ..., bms_err_code: _Optional[int] = ..., bms_min_cell_vol: _Optional[int] = ..., bms_max_cell_vol: _Optional[int] = ..., cms_batt_vol: _Optional[float] = ..., cms_batt_amp: _Optional[float] = ..., cms_chg_req_vol: _Optional[float] = ..., cms_chg_req_amp: _Optional[float] = ..., bms_alm_state_2: _Optional[int] = ..., bms_pro_state_2: _Optional[int] = ...) -> None: ...

class River3SetCommand(_message.Message):
    __slots__ = ("cfg_power_off", "cfg_utc_time", "cfg_utc_timezone", "en_beep", "ac_standby_time", "dc_standby_time", "screen_off_time", "dev_standby_time", "lcd_light", "cfg_dc12v_out_open", "xboost_en", "cms_max_chg_soc", "cms_min_dsg_soc", "cfg_energy_backup", "plug_in_info_ac_in_chg_pow_max", "cfg_ac_out_open", "plug_in_info_pv_dc_amp_max", "cfg_led_mode", "pv_chg_type", "output_power_off_memory")
    CFG_POWER_OFF_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIME_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    EN_BEEP_FIELD_NUMBER: _ClassVar[int]
    AC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    DC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    SCREEN_OFF_TIME_FIELD_NUMBER: _ClassVar[int]
    DEV_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    LCD_LIGHT_FIELD_NUMBER: _ClassVar[int]
    CFG_DC12V_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    XBOOST_EN_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    CFG_ENERGY_BACKUP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    CFG_AC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    CFG_LED_MODE_FIELD_NUMBER: _ClassVar[int]
    PV_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_POWER_OFF_MEMORY_FIELD_NUMBER: _ClassVar[int]
    cfg_power_off: int
    cfg_utc_time: int
    cfg_utc_timezone: int
    en_beep: int
    ac_standby_time: int
    dc_standby_time: int
    screen_off_time: int
    dev_standby_time: int
    lcd_light: int
    cfg_dc12v_out_open: int
    xboost_en: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    cfg_energy_backup: River3CfgEnergyBackup
    plug_in_info_ac_in_chg_pow_max: int
    cfg_ac_out_open: int
    plug_in_info_pv_dc_amp_max: int
    cfg_led_mode: int
    pv_chg_type: int
    output_power_off_memory: int
    def __init__(self, cfg_power_off: _Optional[int] = ..., cfg_utc_time: _Optional[int] = ..., cfg_utc_timezone: _Optional[int] = ..., en_beep: _Optional[int] = ..., ac_standby_time: _Optional[int] = ..., dc_standby_time: _Optional[int] = ..., screen_off_time: _Optional[int] = ..., dev_standby_time: _Optional[int] = ..., lcd_light: _Optional[int] = ..., cfg_dc12v_out_open: _Optional[int] = ..., xboost_en: _Optional[int] = ..., cms_max_chg_soc: _Optional[int] = ..., cms_min_dsg_soc: _Optional[int] = ..., cfg_energy_backup: _Optional[_Union[River3CfgEnergyBackup, _Mapping]] = ..., plug_in_info_ac_in_chg_pow_max: _Optional[int] = ..., cfg_ac_out_open: _Optional[int] = ..., plug_in_info_pv_dc_amp_max: _Optional[int] = ..., cfg_led_mode: _Optional[int] = ..., pv_chg_type: _Optional[int] = ..., output_power_off_memory: _Optional[int] = ...) -> None: ...

class River3SetReply(_message.Message):
    __slots__ = ("action_id", "config_ok", "cfg_utc_time", "cfg_utc_timezone", "en_beep", "ac_standby_time", "dc_standby_time", "screen_off_time", "dev_standby_time", "lcd_light", "cfg_dc12v_out_open", "xboost_en", "cms_max_chg_soc", "cms_min_dsg_soc", "cfg_energy_backup", "plug_in_info_ac_in_chg_pow_max", "dc_out_open", "cfg_ac_out_open", "plug_in_info_pv_dc_amp_max", "cfg_led_mode", "pv_chg_type", "output_power_off_memory")
    ACTION_ID_FIELD_NUMBER: _ClassVar[int]
    CONFIG_OK_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIME_FIELD_NUMBER: _ClassVar[int]
    CFG_UTC_TIMEZONE_FIELD_NUMBER: _ClassVar[int]
    EN_BEEP_FIELD_NUMBER: _ClassVar[int]
    AC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    DC_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    SCREEN_OFF_TIME_FIELD_NUMBER: _ClassVar[int]
    DEV_STANDBY_TIME_FIELD_NUMBER: _ClassVar[int]
    LCD_LIGHT_FIELD_NUMBER: _ClassVar[int]
    CFG_DC12V_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    XBOOST_EN_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    CFG_ENERGY_BACKUP_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_AC_IN_CHG_POW_MAX_FIELD_NUMBER: _ClassVar[int]
    DC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    CFG_AC_OUT_OPEN_FIELD_NUMBER: _ClassVar[int]
    PLUG_IN_INFO_PV_DC_AMP_MAX_FIELD_NUMBER: _ClassVar[int]
    CFG_LED_MODE_FIELD_NUMBER: _ClassVar[int]
    PV_CHG_TYPE_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_POWER_OFF_MEMORY_FIELD_NUMBER: _ClassVar[int]
    action_id: int
    config_ok: bool
    cfg_utc_time: int
    cfg_utc_timezone: int
    en_beep: int
    ac_standby_time: int
    dc_standby_time: int
    screen_off_time: int
    dev_standby_time: int
    lcd_light: int
    cfg_dc12v_out_open: int
    xboost_en: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    cfg_energy_backup: River3CfgEnergyBackup
    plug_in_info_ac_in_chg_pow_max: int
    dc_out_open: int
    cfg_ac_out_open: int
    plug_in_info_pv_dc_amp_max: int
    cfg_led_mode: int
    pv_chg_type: int
    output_power_off_memory: int
    def __init__(self, action_id: _Optional[int] = ..., config_ok: bool = ..., cfg_utc_time: _Optional[int] = ..., cfg_utc_timezone: _Optional[int] = ..., en_beep: _Optional[int] = ..., ac_standby_time: _Optional[int] = ..., dc_standby_time: _Optional[int] = ..., screen_off_time: _Optional[int] = ..., dev_standby_time: _Optional[int] = ..., lcd_light: _Optional[int] = ..., cfg_dc12v_out_open: _Optional[int] = ..., xboost_en: _Optional[int] = ..., cms_max_chg_soc: _Optional[int] = ..., cms_min_dsg_soc: _Optional[int] = ..., cfg_energy_backup: _Optional[_Union[River3CfgEnergyBackup, _Mapping]] = ..., plug_in_info_ac_in_chg_pow_max: _Optional[int] = ..., dc_out_open: _Optional[int] = ..., cfg_ac_out_open: _Optional[int] = ..., plug_in_info_pv_dc_amp_max: _Optional[int] = ..., cfg_led_mode: _Optional[int] = ..., pv_chg_type: _Optional[int] = ..., output_power_off_memory: _Optional[int] = ...) -> None: ...

class River3CfgEnergyBackup(_message.Message):
    __slots__ = ("energy_backup_en", "energy_backup_start_soc")
    ENERGY_BACKUP_EN_FIELD_NUMBER: _ClassVar[int]
    ENERGY_BACKUP_START_SOC_FIELD_NUMBER: _ClassVar[int]
    energy_backup_en: int
    energy_backup_start_soc: int
    def __init__(self, energy_backup_en: _Optional[int] = ..., energy_backup_start_soc: _Optional[int] = ...) -> None: ...

class River3CMSHeartBeatReport(_message.Message):
    __slots__ = ("msg32_2_1", "msg32_2_2")
    MSG32_2_1_FIELD_NUMBER: _ClassVar[int]
    MSG32_2_2_FIELD_NUMBER: _ClassVar[int]
    msg32_2_1: River3CMSStatus1
    msg32_2_2: River3CMSStatus2
    def __init__(self, msg32_2_1: _Optional[_Union[River3CMSStatus1, _Mapping]] = ..., msg32_2_2: _Optional[_Union[River3CMSStatus2, _Mapping]] = ...) -> None: ...

class River3CMSStatus1(_message.Message):
    __slots__ = ("cms_status_misc1", "cms_status_misc2", "cms_status_misc3", "cms_batt_vol_mv", "cms_chg_req_amp", "cms_status_misc4", "cms_max_chg_soc", "cms_min_dsg_soc", "ac_out_freq", "cms_status_misc5", "cms_status_misc6", "cms_chg_rem_time", "cms_dsg_rem_time", "cms_chg_dsg_state", "cms_batt_soc", "bms_is_conn_state", "cms_status_misc7", "cms_status_misc8", "cms_status_misc9", "cms_status_misc10", "cms_status_misc11", "cms_status_misc12", "cms_oil_off_soc")
    CMS_STATUS_MISC1_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC2_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC3_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_VOL_MV_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REQ_AMP_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC4_FIELD_NUMBER: _ClassVar[int]
    CMS_MAX_CHG_SOC_FIELD_NUMBER: _ClassVar[int]
    CMS_MIN_DSG_SOC_FIELD_NUMBER: _ClassVar[int]
    AC_OUT_FREQ_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC5_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC6_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_DSG_REM_TIME_FIELD_NUMBER: _ClassVar[int]
    CMS_CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_BATT_SOC_FIELD_NUMBER: _ClassVar[int]
    BMS_IS_CONN_STATE_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC7_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC8_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC9_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC10_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC11_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC12_FIELD_NUMBER: _ClassVar[int]
    CMS_OIL_OFF_SOC_FIELD_NUMBER: _ClassVar[int]
    cms_status_misc1: int
    cms_status_misc2: int
    cms_status_misc3: int
    cms_batt_vol_mv: int
    cms_chg_req_amp: int
    cms_status_misc4: int
    cms_max_chg_soc: int
    cms_min_dsg_soc: int
    ac_out_freq: int
    cms_status_misc5: int
    cms_status_misc6: int
    cms_chg_rem_time: int
    cms_dsg_rem_time: int
    cms_chg_dsg_state: int
    cms_batt_soc: float
    bms_is_conn_state: _containers.RepeatedScalarFieldContainer[int]
    cms_status_misc7: int
    cms_status_misc8: int
    cms_status_misc9: int
    cms_status_misc10: int
    cms_status_misc11: int
    cms_status_misc12: int
    cms_oil_off_soc: int
    def __init__(self, cms_status_misc1: _Optional[int] = ..., cms_status_misc2: _Optional[int] = ..., cms_status_misc3: _Optional[int] = ..., cms_batt_vol_mv: _Optional[int] = ..., cms_chg_req_amp: _Optional[int] = ..., cms_status_misc4: _Optional[int] = ..., cms_max_chg_soc: _Optional[int] = ..., cms_min_dsg_soc: _Optional[int] = ..., ac_out_freq: _Optional[int] = ..., cms_status_misc5: _Optional[int] = ..., cms_status_misc6: _Optional[int] = ..., cms_chg_rem_time: _Optional[int] = ..., cms_dsg_rem_time: _Optional[int] = ..., cms_chg_dsg_state: _Optional[int] = ..., cms_batt_soc: _Optional[float] = ..., bms_is_conn_state: _Optional[_Iterable[int]] = ..., cms_status_misc7: _Optional[int] = ..., cms_status_misc8: _Optional[int] = ..., cms_status_misc9: _Optional[int] = ..., cms_status_misc10: _Optional[int] = ..., cms_status_misc11: _Optional[int] = ..., cms_status_misc12: _Optional[int] = ..., cms_oil_off_soc: _Optional[int] = ...) -> None: ...

class River3CMSStatus2(_message.Message):
    __slots__ = ("cms_status_misc13", "cms_status_misc14", "cms_status_misc15", "cms_status_misc16", "cms_status_misc17")
    CMS_STATUS_MISC13_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC14_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC15_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC16_FIELD_NUMBER: _ClassVar[int]
    CMS_STATUS_MISC17_FIELD_NUMBER: _ClassVar[int]
    cms_status_misc13: int
    cms_status_misc14: int
    cms_status_misc15: int
    cms_status_misc16: int
    cms_status_misc17: int
    def __init__(self, cms_status_misc13: _Optional[int] = ..., cms_status_misc14: _Optional[int] = ..., cms_status_misc15: _Optional[int] = ..., cms_status_misc16: _Optional[int] = ..., cms_status_misc17: _Optional[int] = ...) -> None: ...

class River3BMSHeartBeatReport(_message.Message):
    __slots__ = ("num", "type", "cell_id", "err_code", "sys_ver", "soc", "vol", "amp", "temp", "open_bms_flag", "design_cap", "remain_cap", "full_cap", "cycles", "soh", "max_cell_vol", "min_cell_vol", "max_cell_temp", "min_cell_temp", "max_mos_temp", "min_mos_temp", "bms_fault", "bq_sys_stat_reg", "tag_chg_amp", "f32_show_soc", "input_watts", "output_watts", "remain_time", "mos_state", "balance_state", "max_vol_diff", "cell_series_num", "cell_vol", "cell_ntc_num", "cell_temp", "hw_ver", "bms_heartbeat_ver", "ecloud_ocv", "bms_sn", "product_type", "product_detail", "act_soc", "diff_soc", "target_soc", "sys_loader_ver", "sys_state", "chg_dsg_state", "all_err_code", "all_bms_fault", "accu_chg_cap", "accu_dsg_cap", "real_soh", "calendar_soh", "cycle_soh", "mos_ntc_num", "mos_temp", "env_ntc_num", "env_temp", "heatfilm_ntc_num", "heatfilm_temp", "cur_sensor_ntc_num", "cur_sensor_temp", "max_env_temp", "min_env_temp", "max_heatfilm_temp", "min_heatfilm_temp", "max_cur_sensor_temp", "min_cur_sensor_temp", "balance_cmd", "remain_balance_time", "afe_sys_status", "mcu_pin_in_status", "mcu_pin_out_status", "bms_alarm_state1", "bms_alarm_state2", "bms_protect_state1", "bms_protect_state2", "bms_fault_state", "accu_chg_energy", "accu_dsg_energy", "pack_sn", "water_in_flag")
    NUM_FIELD_NUMBER: _ClassVar[int]
    TYPE_FIELD_NUMBER: _ClassVar[int]
    CELL_ID_FIELD_NUMBER: _ClassVar[int]
    ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    SYS_VER_FIELD_NUMBER: _ClassVar[int]
    SOC_FIELD_NUMBER: _ClassVar[int]
    VOL_FIELD_NUMBER: _ClassVar[int]
    AMP_FIELD_NUMBER: _ClassVar[int]
    TEMP_FIELD_NUMBER: _ClassVar[int]
    OPEN_BMS_FLAG_FIELD_NUMBER: _ClassVar[int]
    DESIGN_CAP_FIELD_NUMBER: _ClassVar[int]
    REMAIN_CAP_FIELD_NUMBER: _ClassVar[int]
    FULL_CAP_FIELD_NUMBER: _ClassVar[int]
    CYCLES_FIELD_NUMBER: _ClassVar[int]
    SOH_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    MAX_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    BMS_FAULT_FIELD_NUMBER: _ClassVar[int]
    BQ_SYS_STAT_REG_FIELD_NUMBER: _ClassVar[int]
    TAG_CHG_AMP_FIELD_NUMBER: _ClassVar[int]
    F32_SHOW_SOC_FIELD_NUMBER: _ClassVar[int]
    INPUT_WATTS_FIELD_NUMBER: _ClassVar[int]
    OUTPUT_WATTS_FIELD_NUMBER: _ClassVar[int]
    REMAIN_TIME_FIELD_NUMBER: _ClassVar[int]
    MOS_STATE_FIELD_NUMBER: _ClassVar[int]
    BALANCE_STATE_FIELD_NUMBER: _ClassVar[int]
    MAX_VOL_DIFF_FIELD_NUMBER: _ClassVar[int]
    CELL_SERIES_NUM_FIELD_NUMBER: _ClassVar[int]
    CELL_VOL_FIELD_NUMBER: _ClassVar[int]
    CELL_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    CELL_TEMP_FIELD_NUMBER: _ClassVar[int]
    HW_VER_FIELD_NUMBER: _ClassVar[int]
    BMS_HEARTBEAT_VER_FIELD_NUMBER: _ClassVar[int]
    ECLOUD_OCV_FIELD_NUMBER: _ClassVar[int]
    BMS_SN_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_TYPE_FIELD_NUMBER: _ClassVar[int]
    PRODUCT_DETAIL_FIELD_NUMBER: _ClassVar[int]
    ACT_SOC_FIELD_NUMBER: _ClassVar[int]
    DIFF_SOC_FIELD_NUMBER: _ClassVar[int]
    TARGET_SOC_FIELD_NUMBER: _ClassVar[int]
    SYS_LOADER_VER_FIELD_NUMBER: _ClassVar[int]
    SYS_STATE_FIELD_NUMBER: _ClassVar[int]
    CHG_DSG_STATE_FIELD_NUMBER: _ClassVar[int]
    ALL_ERR_CODE_FIELD_NUMBER: _ClassVar[int]
    ALL_BMS_FAULT_FIELD_NUMBER: _ClassVar[int]
    ACCU_CHG_CAP_FIELD_NUMBER: _ClassVar[int]
    ACCU_DSG_CAP_FIELD_NUMBER: _ClassVar[int]
    REAL_SOH_FIELD_NUMBER: _ClassVar[int]
    CALENDAR_SOH_FIELD_NUMBER: _ClassVar[int]
    CYCLE_SOH_FIELD_NUMBER: _ClassVar[int]
    MOS_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    MOS_TEMP_FIELD_NUMBER: _ClassVar[int]
    ENV_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    HEATFILM_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    CUR_SENSOR_NTC_NUM_FIELD_NUMBER: _ClassVar[int]
    CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_ENV_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_HEATFILM_TEMP_FIELD_NUMBER: _ClassVar[int]
    MAX_CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    MIN_CUR_SENSOR_TEMP_FIELD_NUMBER: _ClassVar[int]
    BALANCE_CMD_FIELD_NUMBER: _ClassVar[int]
    REMAIN_BALANCE_TIME_FIELD_NUMBER: _ClassVar[int]
    AFE_SYS_STATUS_FIELD_NUMBER: _ClassVar[int]
    MCU_PIN_IN_STATUS_FIELD_NUMBER: _ClassVar[int]
    MCU_PIN_OUT_STATUS_FIELD_NUMBER: _ClassVar[int]
    BMS_ALARM_STATE1_FIELD_NUMBER: _ClassVar[int]
    BMS_ALARM_STATE2_FIELD_NUMBER: _ClassVar[int]
    BMS_PROTECT_STATE1_FIELD_NUMBER: _ClassVar[int]
    BMS_PROTECT_STATE2_FIELD_NUMBER: _ClassVar[int]
    BMS_FAULT_STATE_FIELD_NUMBER: _ClassVar[int]
    ACCU_CHG_ENERGY_FIELD_NUMBER: _ClassVar[int]
    ACCU_DSG_ENERGY_FIELD_NUMBER: _ClassVar[int]
    PACK_SN_FIELD_NUMBER: _ClassVar[int]
    WATER_IN_FLAG_FIELD_NUMBER: _ClassVar[int]
    num: int
    type: int
    cell_id: int
    err_code: int
    sys_ver: int
    soc: int
    vol: int
    amp: int
    temp: int
    open_bms_flag: int
    design_cap: int
    remain_cap: int
    full_cap: int
    cycles: int
    soh: int
    max_cell_vol: int
    min_cell_vol: int
    max_cell_temp: int
    min_cell_temp: int
    max_mos_temp: int
    min_mos_temp: int
    bms_fault: int
    bq_sys_stat_reg: int
    tag_chg_amp: int
    f32_show_soc: float
    input_watts: int
    output_watts: int
    remain_time: int
    mos_state: int
    balance_state: int
    max_vol_diff: int
    cell_series_num: int
    cell_vol: _containers.RepeatedScalarFieldContainer[int]
    cell_ntc_num: int
    cell_temp: _containers.RepeatedScalarFieldContainer[int]
    hw_ver: str
    bms_heartbeat_ver: int
    ecloud_ocv: int
    bms_sn: str
    product_type: int
    product_detail: int
    act_soc: float
    diff_soc: float
    target_soc: float
    sys_loader_ver: int
    sys_state: int
    chg_dsg_state: int
    all_err_code: int
    all_bms_fault: int
    accu_chg_cap: int
    accu_dsg_cap: int
    real_soh: float
    calendar_soh: float
    cycle_soh: float
    mos_ntc_num: int
    mos_temp: _containers.RepeatedScalarFieldContainer[int]
    env_ntc_num: int
    env_temp: _containers.RepeatedScalarFieldContainer[int]
    heatfilm_ntc_num: int
    heatfilm_temp: _containers.RepeatedScalarFieldContainer[int]
    cur_sensor_ntc_num: int
    cur_sensor_temp: _containers.RepeatedScalarFieldContainer[int]
    max_env_temp: int
    min_env_temp: int
    max_heatfilm_temp: int
    min_heatfilm_temp: int
    max_cur_sensor_temp: int
    min_cur_sensor_temp: int
    balance_cmd: int
    remain_balance_time: _containers.RepeatedScalarFieldContainer[int]
    afe_sys_status: int
    mcu_pin_in_status: int
    mcu_pin_out_status: int
    bms_alarm_state1: int
    bms_alarm_state2: int
    bms_protect_state1: int
    bms_protect_state2: int
    bms_fault_state: int
    accu_chg_energy: int
    accu_dsg_energy: int
    pack_sn: str
    water_in_flag: int
    def __init__(self, num: _Optional[int] = ..., type: _Optional[int] = ..., cell_id: _Optional[int] = ..., err_code: _Optional[int] = ..., sys_ver: _Optional[int] = ..., soc: _Optional[int] = ..., vol: _Optional[int] = ..., amp: _Optional[int] = ..., temp: _Optional[int] = ..., open_bms_flag: _Optional[int] = ..., design_cap: _Optional[int] = ..., remain_cap: _Optional[int] = ..., full_cap: _Optional[int] = ..., cycles: _Optional[int] = ..., soh: _Optional[int] = ..., max_cell_vol: _Optional[int] = ..., min_cell_vol: _Optional[int] = ..., max_cell_temp: _Optional[int] = ..., min_cell_temp: _Optional[int] = ..., max_mos_temp: _Optional[int] = ..., min_mos_temp: _Optional[int] = ..., bms_fault: _Optional[int] = ..., bq_sys_stat_reg: _Optional[int] = ..., tag_chg_amp: _Optional[int] = ..., f32_show_soc: _Optional[float] = ..., input_watts: _Optional[int] = ..., output_watts: _Optional[int] = ..., remain_time: _Optional[int] = ..., mos_state: _Optional[int] = ..., balance_state: _Optional[int] = ..., max_vol_diff: _Optional[int] = ..., cell_series_num: _Optional[int] = ..., cell_vol: _Optional[_Iterable[int]] = ..., cell_ntc_num: _Optional[int] = ..., cell_temp: _Optional[_Iterable[int]] = ..., hw_ver: _Optional[str] = ..., bms_heartbeat_ver: _Optional[int] = ..., ecloud_ocv: _Optional[int] = ..., bms_sn: _Optional[str] = ..., product_type: _Optional[int] = ..., product_detail: _Optional[int] = ..., act_soc: _Optional[float] = ..., diff_soc: _Optional[float] = ..., target_soc: _Optional[float] = ..., sys_loader_ver: _Optional[int] = ..., sys_state: _Optional[int] = ..., chg_dsg_state: _Optional[int] = ..., all_err_code: _Optional[int] = ..., all_bms_fault: _Optional[int] = ..., accu_chg_cap: _Optional[int] = ..., accu_dsg_cap: _Optional[int] = ..., real_soh: _Optional[float] = ..., calendar_soh: _Optional[float] = ..., cycle_soh: _Optional[float] = ..., mos_ntc_num: _Optional[int] = ..., mos_temp: _Optional[_Iterable[int]] = ..., env_ntc_num: _Optional[int] = ..., env_temp: _Optional[_Iterable[int]] = ..., heatfilm_ntc_num: _Optional[int] = ..., heatfilm_temp: _Optional[_Iterable[int]] = ..., cur_sensor_ntc_num: _Optional[int] = ..., cur_sensor_temp: _Optional[_Iterable[int]] = ..., max_env_temp: _Optional[int] = ..., min_env_temp: _Optional[int] = ..., max_heatfilm_temp: _Optional[int] = ..., min_heatfilm_temp: _Optional[int] = ..., max_cur_sensor_temp: _Optional[int] = ..., min_cur_sensor_temp: _Optional[int] = ..., balance_cmd: _Optional[int] = ..., remain_balance_time: _Optional[_Iterable[int]] = ..., afe_sys_status: _Optional[int] = ..., mcu_pin_in_status: _Optional[int] = ..., mcu_pin_out_status: _Optional[int] = ..., bms_alarm_state1: _Optional[int] = ..., bms_alarm_state2: _Optional[int] = ..., bms_protect_state1: _Optional[int] = ..., bms_protect_state2: _Optional[int] = ..., bms_fault_state: _Optional[int] = ..., accu_chg_energy: _Optional[int] = ..., accu_dsg_energy: _Optional[int] = ..., pack_sn: _Optional[str] = ..., water_in_flag: _Optional[int] = ...) -> None: ...

class River3HeaderMessage(_message.Message):
    __slots__ = ("header",)
    HEADER_FIELD_NUMBER: _ClassVar[int]
    header: _containers.RepeatedCompositeFieldContainer[_ecopacket_pb2.Header]
    def __init__(self, header: _Optional[_Iterable[_Union[_ecopacket_pb2.Header, _Mapping]]] = ...) -> None: ...
